feat/fix: currency column
nocodb/nocodb pull request #1687
Opened 2022-04-16 01:59 UTC by mertmit

## Change Summary

Currency locale and currency code can be customized.

Refs: #572 #1042 #1352 #1647

## Change type

- [x] feat: (new feature for the user, not a new feature for build script)
- [x] fix

## Test/ Verification

![image](https://user-images.githubusercontent.com/59797957/163656874-031df015-7ba7-47d9-bafc-8a40bd75b862.png)
![image](https://user-images.githubusercontent.com/59797957/163656958-717513fa-e20d-45d5-8d14-d207cd1835ab.png)

## Additional information

- Need assist on migrating validate field of old currency columns (isCurrency -> isFloat). I didn't marked as breaking change as this is same behaviour with current build.
- #1042 and #1647 fixed for fresh columns
- Country code reference: https://en.wikipedia.org/wiki/ISO_4217

2022-04-16 05:48 UTC, pranavxc requested changes

2022-04-16 05:48 UTC, pranavxc commented on packages/nc-gui/components/project/spreadsheet/components/editColumn.vue
> +      if (this.newColumn.uidt === 'Currency' && this.column?.uidt !== 'Currency') {
Use `UiTypes` enum for referring uidt whenever possible. So in the above case, you can replace `Currency` with `UiTypes.Currency`, where you can import `UiTypes` from `nocodb-sdk` package.

2022-04-18 10:12 UTC, wingkwong reviewed
Just a heads up. We are putting v2 migration stuff in different places. Here's something you should change soon.

1. Move the changes you made in `XcMigrationSource.ts` to `XcMigrationSourceV2.ts`
2. Move `nc_012_add_currency_column.ts` to `migrationsv2` instead of `migrations`. You may also need to change the file name as `nc_012` is being occupied. 

However, we haven't merged it to `develop` branch yet. Will ping you when it is ready.

2022-04-18 15:28 UTC, mertmit commented
I will prepare migrations according to your instructions and wait for your ping to push proper changes updated with latest develop branch.

Meanwhile I updated UI:
![image](https://user-images.githubusercontent.com/59797957/163831647-af8ecc5b-54ca-4a67-ad9c-90f6a7c85ca2.png)

2022-04-18 15:35 UTC, wingkwong commented
@mertmit Now it is in develop branch. Please pull the latest code and merge it accordingly. Thanks.

2022-04-18 16:14 UTC, mertmit commented
**Caution:** The migration still misses changing validate column to 'isFloat' for existent currency columns.

2022-04-23 05:14 UTC, wingkwong commented
@mertmit Marking it as Draft first. Please request a review again when it is ready.

2022-04-23 11:19 UTC, mertmit commented
https://github.com/nocodb/nocodb/pull/1687/commits/202df2d731727e15e1a7e6c5cead7a233d37dd91
on this commit I've created a custom validators file as this might come in handy in future (if we want to bypass any function provided by validate or want to remap as in this case)

2022-04-25 03:41 UTC, wingkwong commented
@mertmit Please rebase and resolve the conflicts first.

2022-04-25 20:38 UTC, o1lab commented
Im wondering whether it would be good idea to not keep separate table for currency. That way we don't end up creating a lot of tables for each types. A simple json column or text column (stringify json) would be sufficient ? @wingkwong @pranavxc

2022-04-26 03:35 UTC, wingkwong commented on packages/nocodb/src/lib/noco-models/Column.ts
> +        currs = await ncMeta.metaList2(null, null, MetaTable.COL_ROLLUP, {
I think it should be `COL_CURRENCY` instead of `COL_ROLLUP`

2022-04-26 03:39 UTC, wingkwong commented
> Im wondering whether it would be good idea to not keep separate table for currency. That way we don't end up creating a lot of tables for each types. A simple json column or text column (stringify json) would be sufficient ? @wingkwong @pranavxc

@mertmit please correct me if I'm wrong.

I think the table is not for storing all the possible currency options but storing the meta currency (locale & code) that users choose. I think keeping it in a separate table would make it more clean.

2022-04-26 04:41 UTC, mertmit commented
@wingkwong yes it only keeps colOptions (column_id, currency_locale, currency_code for currency) in created meta table.
@o1lab actually this is how we handle colOptions for other columns with colOptions. (formula, lookup etc.)

2022-04-28 08:16 UTC, wingkwong commented
@mertmit Please rebase and request review again if it's ready. Thanks.

2022-04-28 16:24 UTC, mertmit commented
@wingkwong ready for a review. Thanks.

2022-04-29 07:51 UTC, mertmit commented
> https://github.com/nocodb/nocodb/pull/1687/commits/202df2d731727e15e1a7e6c5cead7a233d37dd91
> on this commit I've created a custom validators file as this might come in handy in future (if we want to bypass any function provided by validate or want to remap as in this case)

@wingkwong This note left from first state I reverted this change, now it is handled within custom validators which I stated in this comment. You can check the commit in this comment to review validation.

2022-04-30 08:25 UTC, wingkwong approved these changes

2022-05-24 06:20 UTC, pranavxc approved these changes

2022-05-24 06:21 UTC, merged