feat(gui-v2): duration cell
nocodb/nocodb pull request #2625
Opened 2022-07-11 05:42 UTC by wingkwong

## Change Summary

- [x] Basic Rendering
- [ ] Saving

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [ ] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [x] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

2022-07-11 11:01 UTC, pranavxc requested changes

2022-07-11 11:43 UTC, wingkwong commented on packages/nc-gui/helpers/viewIcons.js
> +export default {
@pranavxc I haven't used it in v2. I added it because I wanted to run v1 on gui-v2 branch only.

2022-07-11 12:08 UTC, pranavxc commented on packages/nc-gui/helpers/viewIcons.js
> +export default {
oh sorry... ignore it ...

2022-07-11 16:34 UTC, pranavxc approved these changes

2022-07-12 06:51 UTC, bcakmakoglu requested changes

2022-07-12 08:58 UTC, bcakmakoglu approved these changes

2022-07-12 09:44 UTC, merged