feat/add-dynamic-feedback-form-submission
nocodb/nocodb pull request #2641
Opened 2022-07-11 14:40 UTC by mustafapc19

## Change Summary

Feedback form url has now `validity_till` time, after which new feedback form will be fetched. 

Ref: #2640, [#170](https://github.com/nocodb/noco-generals/issues/170)

## Change type

- [x] feat: (new feature for the user, not a new feature for build script)
- [ ] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

2022-07-12 07:23 UTC, o1lab commented on packages/nocodb/src/lib/meta/api/utilApis.ts
> +  await axios
Lose await since you are using then.

2022-07-12 09:58 UTC, wingkwong requested changes

2022-07-12 09:58 UTC, wingkwong commented on packages/nc-gui/components/FeedbackForm.vue
> +        return this.$store.state.settings.feedbackForm.isShown;
The form is hidden even isShown is true.

```json
{
    "url": "https://docs.google.com/forms/d/e/1FAIpQLSeTlAfZjszgr53lArz3NvUEnJGOT9JtG9NAU5d0oQwunDS2Pw/viewform?embedded=true",
    "createdAt": "2022-07-11T14:11:37.000Z",
    "isShown": true,
    "validTill": "2022-07-19T00:00:01.000Z"
}
```

This line should be `return !this.$store.state.settings.feedbackForm.isShown;` as the condition is `feedbackFormHidden`.

2022-07-13 08:28 UTC, wingkwong reviewed
The logic looks fine but the naming for `isShown` is confusing. If users don't close it, `isShown` is `false` while the form actually is shown.

2022-07-13 09:10 UTC, wingkwong approved these changes

2022-07-14 12:13 UTC, mertmit approved these changes

2022-07-15 14:03 UTC, merged