vue3: Added phone number cell
nocodb/nocodb pull request #2925
Opened 2022-08-01 09:35 UTC by mustafapc19

Ref: #2922 

This is just for the time being, a `Text` cell as it is in `nc-gui` v1.

UI:

![image](https://user-images.githubusercontent.com/35809690/182119253-a4485305-d069-4c6f-824c-7868e62b8e2d.png)

2022-08-01 09:52 UTC, wingkwong requested changes
Please also include an icon for `CellPhoneNumber` in `components/smartsheet-header/CellIcon.vue`. In v1, we're using `mdi:file-phone`. 

See https://icones.js.org/collection/mdi?s=mdi-file-phone

2022-08-01 09:52 UTC, wingkwong commented on packages/nc-gui-v2/components/cell/PhoneNumber.vue
> +textarea {
Use windicss. `@apply ...`

2022-08-01 09:52 UTC, wingkwong commented on packages/nc-gui-v2/components/cell/PhoneNumber.vue
> +const localState = computed({
Try `useVModel`?

2022-08-01 14:16 UTC, mustafapc19 commented
@wingkwong Have added the icon

2022-08-02 04:34 UTC, wingkwong commented
Please rebase, resolve conflicts & run lint.

2022-08-02 04:36 UTC, wingkwong commented on packages/nc-gui-v2/components/cell/PhoneNumber.vue
> +  (event: 'update:modelValue', model: number): void
should string be also allowed? e.g `+15614390540`

2022-08-02 05:47 UTC, wingkwong approved these changes

2022-08-02 05:47 UTC, merged