feat(gui-v2): Grid operations
nocodb/nocodb pull request #2947
Opened 2022-08-02 06:26 UTC by pranavxc

## Change Summary

Provide summary of changes with issue number if any.

## Change type

- [x] feat: (new feature for the user, not a new feature for build script)
- [ ] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

2022-08-02 13:52 UTC, dstala commented
- [x] Row delete
- [x] Multiple rows select and delete
- [ ] Add a new row
- [ ] Column delete
- [ ] Set column as primary ( todo: need to highlight the cell )
- [ ] Add debounce to avoid frequent API calls
- Keyboard navigations
    - [ ] Tab / Shift + Tab to navigate through cells
    - [ ] Arrow key for navigating through cell
    - [ ] Enter key for making editable
    - [ ] Delete to clear the cell value
- Context menu
    - [ ] For row delete
    - [ ] Multiple row delete
    - [ ] Clear cell
    - [ ] Insert new row

2022-08-03 04:18 UTC, dstala commented
@pranavxc : open items summarised here

- [ ] Primary value: highlight cell
- [ ] Increase de-bounce timeout; skip de-bounce for decimal
- [ ] Enter key to mark cell as editable
- [ ] Support for click & type on cell
- [ ] Right click menu persists during the following set of events
  -  right-click, do not select any option
  - click on edit column; edit menu appears & right-click menu doesn't disappear
  
![Screenshot 2022-08-03 at 9 43 01 AM](https://user-images.githubusercontent.com/86527202/182523145-e0608aa2-fa56-4ac7-aa6d-f940aa1a8021.png)

2022-08-03 07:51 UTC, bcakmakoglu requested changes

2022-08-03 07:51 UTC, bcakmakoglu commented on packages/nc-gui-v2/components/smartsheet-header/Cell.vue
> +import { Modal } from 'ant-design-vue'
unused import

2022-08-03 07:51 UTC, bcakmakoglu commented on packages/nc-gui-v2/components/smartsheet-header/Menu.vue
> +    title: h('div', { innerHTML: `Do you want to delete <span class="font-weight-bold">'${column?.title}'</span> column ?` }),
instead of `innerHTML` use the 3rg argument for `h` and pass the string as a slot.

2022-08-03 10:59 UTC, merged