vue3: Added gallery view
nocodb/nocodb pull request #3021
Opened 2022-08-05 14:26 UTC by mustafapc19

Ref: #2631 

UI:
![image](https://user-images.githubusercontent.com/35809690/183097814-d4eefc07-2576-4f3e-b1b8-d3fcb29576a5.png)

2022-08-06 09:43 UTC, o1lab commented
Confirming if multiple images within a card mean - we can go through images at the card level?

2022-08-07 19:05 UTC, bcakmakoglu requested changes

2022-08-07 19:05 UTC, bcakmakoglu commented on packages/nc-gui-v2/components/smartsheet/Gallery.vue
> +  <div class="flex flex-col h-100 min-h-0 w-100">
don't use `h-100` or `w-100` - those are vuetify styles.
Use `h-full` and `w-full` - TailwindCSS classes.

2022-08-07 19:05 UTC, bcakmakoglu commented on packages/nc-gui-v2/components/smartsheet/Gallery.vue
> +    <div class="nc-gallery-container min-h-0 flex-1 grid grid-cols-4 gap-x-4 gap-y-4 my-4 px-3">
`gap-x-4` and gap-y-4` are sort of redundant. Just use `gap-4`

2022-08-08 04:58 UTC, mustafapc19 commented
@o1lab No right now only the first image is shown as it is in v1. Should we add a carousal like flow to show multiple images?

2022-08-08 05:19 UTC, mustafapc19 commented
@o1lab I missed the image carousal in v1. Will add it here as well 👍

2022-08-09 14:16 UTC, merged