vu3: Added share view
nocodb/nocodb pull request #3083
Opened 2022-08-11 11:32 UTC by mustafapc19

Ref: #3038 

Work left:
(Toolbar)
- Integrate `fields`
- Integrate `sort`
- Integrate `filter`
- Integrate `more`

UI:
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/35809690/184124323-35119175-1689-425f-9e8b-313eb84c81a8.png">

2022-08-15 06:02 UTC, pranavxc requested changes

2022-08-15 06:23 UTC, pranavxc commented on packages/nc-gui-v2/composables/useSharedView.ts
> +const paginationData = ref<PaginatedType>({ page: 1, pageSize: 25 })
Why are all the refs outside the composable? If you want to share the state use `useState`.

2022-08-15 07:25 UTC, dstala commented
- Observations `Shared Grid View`
- [ ] Entire shared screen is grayed out. Intended?
- [ ] Error on expanding cell for LTAR field
  
![Screenshot 2022-08-15 at 12 43 48 PM (2)](https://user-images.githubusercontent.com/86527202/184592376-4f78b48e-670b-4526-b30d-70151d19392d.png)

- [ ] `Show System Fields` was disabled in Shared view (v1)
  
<img width="429" alt="Screenshot 2022-08-15 at 12 48 01 PM" src="https://user-images.githubusercontent.com/86527202/184592708-ac8b6f17-80dc-41d3-ab34-f79caa3ba1f7.png">

- [ ] Expand row- error; was disabled in v1
  
![Screenshot 2022-08-15 at 12 50 36 PM](https://user-images.githubusercontent.com/86527202/184592969-c8c13788-f630-4ee8-b87b-e16b7a73037e.png)

- [ ] Disable context-menu, check-box to select
  
![Screenshot 2022-08-15 at 12 50 21 PM](https://user-images.githubusercontent.com/86527202/184592980-e4f9f2e8-b4ad-4199-ae35-d49e76cb24a6.png)

- [ ] View name not displayed

- Verified
- [ ] Field hide / re-order
- [ ] Sort
- [ ] Filter
- [ ] Download files
- [ ] RO fields

2022-08-15 08:59 UTC, dstala requested changes
https://github.com/nocodb/nocodb/pull/3083

2022-08-16 04:27 UTC, mustafapc19 commented
@dstala Regarding some of the cell issues. Its due to cell not configured for read only mode. Which is out of scope for this PR.

And can we ignore the issues of this PR for now and merge?(Unless its breaking stuff) This pr is touching on a lot files and had a lot of conflicts last time. And seems to be in conflict again. i.e I think I did disable expanded row view but seems to slip back in during conflict resolution. Will send a PR again as a followup?

2022-08-16 04:28 UTC, dstala commented
> @dstala Regarding some of the cell issues. Its due to cell not configured for read only mode. Which is out of scope for this PR.
> 
> And can we ignore the issues of this PR for now and merge?(Unless its breaking stuff) This pr is touching on a lot files and had a lot of conflicts last time. And seems to be in conflict again. i.e I think I did disable expanded row view but seems to slip back in during conflict resolution. Will send a PR again as a followup?

@mustafapc19 sure. We can merge these changes & work on the rest of the items in a new PR

2022-08-16 04:29 UTC, dstala approved these changes

2022-08-16 04:30 UTC, mustafapc19 commented
@bcakmakoglu While reviewing can you specify the deal breakers? Will only include them and include the rest of the reviews in a follow up PR.

2022-08-16 06:58 UTC, bcakmakoglu requested changes

2022-08-16 06:58 UTC, bcakmakoglu commented on packages/nc-gui-v2/components/shared-view/AskPassword.vue
> +}
Interface goes above props

2022-08-16 06:58 UTC, bcakmakoglu commented on packages/nc-gui-v2/components/shared-view/AskPassword.vue
> +const emit = defineEmits(['update:modelValue'])
some space in between vars and imports would be nice

2022-08-16 06:58 UTC, bcakmakoglu commented on packages/nc-gui-v2/components/shared-view/Form.vue
> +console.log(fields)
can be removed I assume

2022-08-16 06:58 UTC, bcakmakoglu commented on packages/nc-gui-v2/components/shared-view/Form.vue
> +        }}</a-typography-title>
Formatting
Should be
```html
<a-typography-title class="border-b-1 border-gray-100 w-full pb-3" :level="1">
	{{ sharedView.view.heading }}
</a-typography-title>

2022-08-16 06:58 UTC, bcakmakoglu commented on packages/nc-gui-v2/components/smartsheet/Toolbar.vue
> +import { IsPublicInj } from '~/context'
Can be shorted to just one import line from `'#imports'`

2022-08-16 06:58 UTC, bcakmakoglu commented on packages/nc-gui-v2/composables/useViewData.ts
> +import { IsPublicInj } from '~/context'
-> `'#imports'`

2022-08-16 06:58 UTC, bcakmakoglu commented on packages/nc-gui-v2/composables/useViewFilters.ts
> +import { IsPublicInj, ReloadViewDataHookInj } from '~/context'
-> `'#imports'`

2022-08-16 06:58 UTC, bcakmakoglu commented on packages/nc-gui-v2/composables/useViewSorts.ts
> +import { IsPublicInj, ReloadViewDataHookInj } from '~/context'
-> `'#imports'`

2022-08-16 06:58 UTC, bcakmakoglu commented on packages/nc-gui-v2/pages/[projectType]/form/[viewId].vue
> +import type { TableType } from 'nocodb-sdk/build/main'
-> `'nocodb-sdk'`

2022-08-16 06:58 UTC, bcakmakoglu commented on packages/nc-gui-v2/pages/[projectType]/form/[viewId].vue
> +import { useRoute } from '#imports'
-> `'#imports'`

2022-08-16 06:58 UTC, bcakmakoglu commented on packages/nc-gui-v2/pages/[projectType]/form/[viewId].vue
> +definePageMeta({
spacing

2022-08-16 06:58 UTC, bcakmakoglu commented on packages/nc-gui-v2/pages/[projectType]/form/[viewId].vue
> +// useSmartsheetRowStore()
Can be removed

2022-08-16 06:58 UTC, bcakmakoglu commented on packages/nc-gui-v2/pages/[projectType]/view/[viewId].vue
> +definePageMeta({
spacing

2022-08-16 06:58 UTC, bcakmakoglu commented on packages/nc-gui-v2/pages/[projectType]/view/[viewId].vue
> +
remove space

2022-08-16 06:58 UTC, bcakmakoglu commented on packages/nc-gui-v2/pages/[projectType]/view/[viewId].vue
> +import { ReadonlyInj, ReloadViewDataHookInj } from '~/context'
-> `'#imports'`

2022-08-16 09:53 UTC, merged