vue3: Added showing error message on invalid url entry
nocodb/nocodb pull request #3185
Opened 2022-08-16 14:07 UTC by mustafapc19

Ref: https://github.com/nocodb/nocodb/issues/2980#issuecomment-1208348855

Screenshot:
<img width="428" alt="image" src="https://user-images.githubusercontent.com/35809690/184900023-a95c019f-c727-47b7-b1c6-d4c073501e38.png">

2022-08-17 03:05 UTC, wingkwong requested changes
1. Validation should be only performed when users have selected `Accept only valid URL`. Now validation is triggered anyway.

![image](https://user-images.githubusercontent.com/35857179/185025472-3071c68b-51f8-4b30-aec1-8c0bafc47d18.png)
 
2. The value shouldn't be saved if the URL is invalid. Now error message is shown but the value is stored. (you can refresh / reload to see it)

2022-08-17 05:04 UTC, mustafapc19 commented
@wingkwong Regarding 2nd point can you tell me the steps to reproduce? In my case when I am reloading/refreshing its reverting to the last saved/validated value.

2022-08-17 05:18 UTC, wingkwong commented
Now it seems fine for the second point. However, with `Accept only valid URL` enabled, I couldn't set it empty.

2022-08-17 05:23 UTC, wingkwong commented
Another thought 

- Create a URL column with `Accept only valid URL` disabled
- Input data with some invalid URL
- Edit the column. Enabled `Accept only valid URL`

In this case, I think it'd be great if those cells have some indicators to show that they are invalid so that users can easily spot them to change the values.

2022-08-17 13:55 UTC, mustafapc19 commented
@wingkwong Have added ui indication for URL being invalid. Attached the screenshot in the PR description.

2022-08-18 03:46 UTC, wingkwong reviewed
`qweq` shouldn't be a hyperlink. (Accept only valid URL: false)

v2:

![image](https://user-images.githubusercontent.com/35857179/185288729-80c5c00c-f989-4234-afff-44b47859f801.png)

v1: 
![image](https://user-images.githubusercontent.com/35857179/185288741-0b273a81-2f98-455d-bb04-b41339936009.png)

2022-08-18 03:46 UTC, wingkwong commented on packages/nc-gui-v2/components/cell/Url.vue
> +          <MaterialSymbolsWarning />
Suggest to color it.

![image](https://user-images.githubusercontent.com/35857179/185288545-71c2d932-0b5f-4792-8684-875a8fc792d5.png)

2022-08-18 05:02 UTC, wingkwong approved these changes

2022-08-18 05:02 UTC, merged