feat(gui-v2): add smtp rejectUnauthorized
nocodb/nocodb pull request #3244
Opened 2022-08-19 09:31 UTC by wingkwong

## Change Summary

ref: #2276

- add `rejectUnauthorized` option for smtp
- change secure to checkbox

## Change type

- [x] feat: (new feature for the user, not a new feature for build script)
- [ ] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

![image](https://user-images.githubusercontent.com/35857179/185589745-01e3528d-7b51-4df7-8d16-bf75ea38fcc3.png)

2022-08-19 10:38 UTC, pranavxc requested changes

2022-08-19 11:03 UTC, wingkwong commented on packages/nocodb/src/lib/plugins/smtp/SMTP.ts
> +      secure: this.input?.secure,
Covered here 

https://github.com/nocodb/nocodb/blob/b13297030683963b0a0eb94a422f489d004d5f10/packages/nc-gui-v2/components/dashboard/settings/app-store/AppInstall.vue#L106-L111

2022-08-19 11:06 UTC, pranavxc commented on packages/nocodb/src/lib/plugins/smtp/SMTP.ts
> +      secure: this.input?.secure,
What about the backend while initializing SMTP? For example if value is `'false'`

2022-08-19 11:11 UTC, wingkwong commented on packages/nocodb/src/lib/plugins/smtp/SMTP.ts
> +      secure: this.input?.secure,
That's a good point. Added it back.

2022-08-19 14:24 UTC, pranavxc approved these changes

2022-08-23 03:03 UTC, wingkwong commented
Skipping v1 cypress.

2022-08-23 03:03 UTC, merged