Make shared views editable
nocodb/nocodb pull request #3374
Opened 2022-08-27 18:18 UTC by dolsem

## Change Summary

Allows logged in users to edit data in shared views. This is a draft implementation, please lmk what you think!

## Change type

- [x] feat: (new feature for the user, not a new feature for build script)
- [ ] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Makes it possible insert and delete new rows, edit existing cells in shared views when the user is logged in. Enables the context menu.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

2022-08-27 18:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nocodb/nocodb?pullRequest=3374) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nocodb/nocodb?pullRequest=3374) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nocodb/nocodb?pullRequest=3374) it.</sub>

2022-08-27 18:39 UTC, bcakmakoglu requested changes

2022-08-27 18:39 UTC, bcakmakoglu commented on packages/nc-gui-v2/composables/useGlobal/state.ts
> +  const isAuthenticated = !!token.value
There's a getter `signedIn` that can be used instead.

2022-08-28 01:56 UTC, dolsem commented
Oops, didn't mean to remove @pranavxc from reviewers

2022-08-29 08:34 UTC, wingkwong approved these changes

2022-08-29 09:49 UTC, bcakmakoglu approved these changes

2022-08-29 09:51 UTC, merged

2022-08-29 09:52 UTC, pranavxc approved these changes

2023-08-24 17:25 UTC, onejgordon commented
Has this been released? The [documentation](https://docs.nocodb.com/setup-and-usages/share-view) doesn't refer to edit access of shared views.