New Crowdin updates
nocodb/nocodb pull request #3556
Opened 2022-09-08 09:34 UTC by o1lab

2022-09-08 15:41 UTC, dstala commented
@wingkwong - help us correct strings for below translation 
  zh_Hans = '大陆简体',
  zh_Hant = '臺灣正體',

First one is for `Chinese (simplified)`, second is for `Chinese (traditional)`
For now, I just placed text as is from `zh-cn` and `zh-tw`

2022-09-12 03:43 UTC, wingkwong requested changes

2022-09-12 03:43 UTC, wingkwong commented on packages/nc-gui/lib/enums.ts
> +  zh_Hans = '大陆简体',
Use `简体中文`

2022-09-12 03:43 UTC, wingkwong commented on packages/nc-gui/lib/enums.ts
> +  zh_Hant = '臺灣正體',
Use `繁體中文`

2022-09-13 04:59 UTC, merged