Fix: expanded form view row insert bug
nocodb/nocodb pull request #3569
Opened 2022-09-09 13:32 UTC by pranavxc

## Change Summary

- Adding a new row should reflect in the grid view
- After adding new row LTAR data should be present in expanded form
- Unlinking LTAR should remove it from expanded form

re #3565 #3566

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [x] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

2022-09-12 09:14 UTC, bcakmakoglu requested changes

2022-09-12 09:14 UTC, bcakmakoglu commented on packages/nc-gui/components/smartsheet/Grid.vue
> +  console.log(rowRefs)
Log can be removed

2022-09-12 09:14 UTC, bcakmakoglu commented on packages/nc-gui/components/smartsheet/Grid.vue
> +-->
Formatting seems broken

2022-09-12 09:14 UTC, bcakmakoglu commented on packages/nc-gui/components/tabs/Smartsheet.vue
> +// )
Can be removed I assume?

2022-09-12 09:14 UTC, bcakmakoglu commented on packages/nc-gui/components/virtual-cell/BelongsTo.vue
> +const reloadRowTrigger = inject(ReloadRowDataHookInj, createEventHook())!
`!` can be removed if you provide a default value (i.e. `createEventHook()`)

2022-09-12 09:14 UTC, bcakmakoglu commented on packages/nc-gui/components/virtual-cell/components/ListItems.vue
> +        </a-button>
Formatting is off

2022-09-12 09:28 UTC, bcakmakoglu approved these changes

2022-09-13 03:31 UTC, wingkwong approved these changes

2022-09-13 03:31 UTC, merged