Feat: URL for expanded row
nocodb/nocodb pull request #3655
Opened 2022-09-15 06:55 UTC by pranavxc

## Change Summary

Provide summary of changes with issue number if any.

## Change type

- [x] feat: (new feature for the user, not a new feature for build script)
- [ ] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

2022-09-16 07:14 UTC, dstala approved these changes
@pranavxc 
- ~~Consider enabling the `comment` section by default in expanded record drawer~~ This will slow it down
- ~~Consider showing `hidden columns` as discussed (separate PR may be)~~ Ya can be later
- If `row ID` is invalid, skip opening `expand record` draw

2022-09-17 08:20 UTC, bcakmakoglu requested changes

2022-09-17 08:20 UTC, bcakmakoglu commented on packages/nc-gui/components/smartsheet/Gallery.vue
> +import { extractPkFromRow } from '~/utils'
-> `'#imports'`

2022-09-17 08:20 UTC, bcakmakoglu commented on packages/nc-gui/components/smartsheet/Grid.vue
> +import { useRoute } from '#app'
-> `'#imports'`

2022-09-17 08:20 UTC, bcakmakoglu commented on packages/nc-gui/components/smartsheet/Grid.vue
> +import { extractPkFromRow } from '~/utils'
-> '#imports'

2022-09-17 08:20 UTC, bcakmakoglu commented on packages/nc-gui/components/smartsheet/expanded-form/index.vue
> +import { useRouter } from '#app'
-> '#imports'

2022-09-20 05:59 UTC, wingkwong reviewed
1. sanitise `route.query.rowId`? 
2. should the pagination also be changed when I use this URL? For example, rowId = 45 (the 20th record on page 2 with size page 25), then the page should be navigated to Page 2. Currently it's always page 1.

2022-09-21 07:53 UTC, wingkwong approved these changes

2022-09-21 08:21 UTC, merged