chore(nc-gui): add components.d.ts to eslint ignore patterns
nocodb/nocodb pull request #3703
Opened 2022-09-19 10:31 UTC by bcakmakoglu

## Change Summary

Provide summary of changes with issue number if any.

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [ ] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

2022-09-19 14:04 UTC, wingkwong approved these changes

2022-09-19 14:05 UTC, wingkwong commented
Sorry. Just realise that it's a draft. Will take a look again when it's ready for review.

2022-09-19 14:07 UTC, bcakmakoglu commented
@wingkwong Yeah I reverted from PR to draft because I noticed some problems with `useState` and the project permissions which made it impossible to use a single computed prop.

I refactored it, so now it should work as expected and consume a bit less memory because we keep a single instead of multiple states.

But let's wait for CI/CD 😄

2022-09-23 07:31 UTC, pranavxc reviewed
Please do a rebase and push.

2022-09-23 09:34 UTC, pranavxc requested changes

2022-09-23 09:34 UTC, pranavxc commented on packages/nc-gui/composables/useRoles/index.ts
> +            'xc-shared-base-id': projectId,
The `projectId` and `shared-base-id` are not the same, It's a unique UUID mapped to the project. 

The above line needs to be replaced with `'xc-shared-base-id': route.params.projectId`

2022-09-23 10:41 UTC, merged