Fix: Grid view - save new row only when all required cell values provided
nocodb/nocodb pull request #3953
Opened 2022-10-06 10:00 UTC by pranavxc

## Change Summary

 re #3696 

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [x] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

2022-10-09 07:53 UTC, wingkwong reviewed
Let's say I've column A, B, C, and D where C & B are required cells.

Case 1. Fill in A & B only. C & D are highlighted. Cell values are not saved which is expected.
Case 2. Fill in A, B, C & D. Cell values are saved which is expected.
Case 3. After Case 2, remove values from C & D. Cell values are saved. (Is it expected in this case? or the value becomes empty rather than NULL so they are considered as filled?)

2022-10-09 10:55 UTC, pranavxc commented
> Let's say I've column A, B, C, and D where C & B are required cells.
> 
> Case 1. Fill in A & B only. C & D are highlighted. Cell values are not saved which is expected. Case 2. Fill in A, B, C & D. Cell values are saved which is expected. Case 3. After Case 2, remove values from C & D. Cell values are saved. (Is it expected in this case? or the value becomes empty rather than NULL so they are considered as filled?)


We are deciding the required field based on the database table field's `not null` attribute, if it's true need to be a non-null value and it can be an empty string as well.

2022-10-10 06:40 UTC, bcakmakoglu requested changes

2022-10-10 06:40 UTC, bcakmakoglu commented on packages/nc-gui/composables/useExpandedFormStore.ts
> +import { populateInsertObject } from '~/utils'
-> `'#imports'` 😉

2022-10-10 06:40 UTC, bcakmakoglu commented on packages/nc-gui/composables/useViewData.ts
> +import { useMetas } from '~/composables/useMetas'
-> `'#imports'`

2022-10-10 07:24 UTC, wingkwong approved these changes

2022-10-10 07:29 UTC, bcakmakoglu approved these changes

2022-10-10 09:18 UTC, merged