feat: OpenID Connect authentication
nocodb/nocodb pull request #3979
Opened 2022-10-08 09:15 UTC by kobim

## Change Summary

Add the option to configure an OpenID Connect identity provider as a sign-in option.

Resolves #742

## Change type

- [x] feat: (new feature for the user, not a new feature for build script)
- [ ] fix: (bug fix for the user, not a fix to a build script)
- [x] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

### Without any modifications

- [x] Sign in with email & password
- [x] Sign up with email & password

### Defining an OIDC provider

- [x] Login screen without a display name

<img width="535" alt="Login without a display name" src="https://user-images.githubusercontent.com/679761/194699478-1297a8fa-750f-444a-ba18-18b1013747e4.png">

- [x] Signup screen without a display name

- [x] Login screen with a display name

<img width="525" alt="Login with a display name" src="https://user-images.githubusercontent.com/679761/194699508-2015c1ef-e587-430e-830e-38fed336fd7c.png">

- [x] Signup screen with a display name
- [x] The first signup assigns the *Owner* role to the new user.
- [x] Invited users with the same email defined by the IdP can accept invitations.

## Additional information / screenshots (optional)

### Forcing the IdP

When the provider is set, it overrides the option to use another identity method (such as email & password or Google Login).
Is this the expected behavior? I would say organizations want to restrict access to their installations, which is the appropriate way to ensure only the IdP will be able to dictate who should be able to login.

2022-10-08 09:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nocodb/nocodb?pullRequest=3979) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nocodb/nocodb?pullRequest=3979) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nocodb/nocodb?pullRequest=3979) it.</sub>

2022-10-08 09:37 UTC, bcakmakoglu commented
Thanks for your contribution :)
We'll take a look but so far this looks nice 👍

2022-10-08 11:25 UTC, bcakmakoglu requested changes

2022-10-08 11:25 UTC, bcakmakoglu commented on packages/nc-gui/composables/useGlobal/state.ts
> +    oidcAuthName: '',
Use `null` instead of an empty string as initial value, that way we don't need to check against empty strings in the template later on.

2022-10-08 11:25 UTC, bcakmakoglu commented on packages/nc-gui/pages/signup/[[token]].vue
> +        <a-form v-if="appInfo.oidcAuthName == ''" ref="formValidator" :model="form" layout="vertical" no-style @finish="signUp">
Relating to the comment above, if you use `null` as the default you can replace this with `v-if="!appInfo.oidcAuthName"`

2022-10-08 11:25 UTC, bcakmakoglu commented on packages/nc-gui/pages/signup/[[token]].vue
> +          v-if="appInfo.oidcAuthName != ''"
This could be changed to just be `v-if="appInfo.oidcAuthName"`

2022-10-08 11:25 UTC, bcakmakoglu commented on packages/nocodb/src/lib/meta/api/utilApis.ts
> +      '';
Return `null` as auth name instead of empty string so we can enforce the checks as mentioned above.

2022-10-20 12:11 UTC, syji35 commented
Thanks for the PR. Is it possible to merge for the next release ?  
We are waiting for this 👍

2022-11-08 10:06 UTC, syji35 commented
@o1lab : What is missing to move the pull request forward ?

2022-11-08 10:37 UTC, o1lab commented
First up, thank you @kobim for this PR. Most products offer SSO & SAML as paid features. We are offering google-auth SSO for free already. Hence we are discussing whether this should be in our free version or not. @kobim @syji35 - I understand SAML is not part of openid auth. Could you please confirm.

2022-11-08 12:39 UTC, syji35 commented
> First up, thank you @kobim for this PR. Most products offer SSO & SAML as paid features. We are offering google-auth SSO for free already. Hence we are discussing whether this should be in our free version or not. @kobim @syji35 - I understand SAML is not part of openid auth. Could you please confirm.

I Confirm

2022-11-22 13:45 UTC, timmwille commented
> SAML and OpenID Connect are two completely different approaches to single sign on. OIDC would not only allow developers and home users to integrate with existing user stores but also, if implemented correctly, would allow developers to build plugins and integrations that leverage OIDC to deliver a smooth experience for users as, for example, a Nextcloud plugin.
> 
> Generally speaking, SSO is not a business only feature, it's a core security feature just as much as users and RBAC are.

I agree much, if there is any chance to include this in the near future I would appreciate it very much and recommend within our non-profit association it requires OIDC. If there is anything we can do to help, I would reach out. 
This is kind of the current discussion between alternatives and I would love to promote NocoDB instead.

2022-11-22 16:16 UTC, ja0nz commented
Came here to boost this PR as well❤️ I believe OIDC offers some compelling benefits regarding service integration and potential extensibility and should be treated on par with password auth. Advanced SAML and RBAC features could instead fit well into the paid version.

2022-11-28 19:35 UTC, almereyda commented
The last comment expresses very well how SAML and OIDC are very often approached in other projects of the open source world. This is to differentiate between Free Software, which intents to liberate all aspects of an application, and open-core business models, where the open core is a working, tested and standards compliant implementation, and enterprise features, like SSO, are sold atop. Please consider supporting OIDC for secure identity federation also for small-scale users.

As a small not-for-profit organisation, we also have to second @timmwille's comment above.

2022-11-30 08:19 UTC, AlexM4H commented
Who takes care of the Playwright test errors?

2022-12-01 11:07 UTC, moedn commented
Good afternoon nocodb folks (@o1lab) :) It would be really nice to have a decision here: Does nocodb want this PR or not? Currently, I'm seeing a lot of people waiting, not only for the PR, but for a general statement how open source nocodb wants to be (and why it wanted to be open source in the first place). This piece of software would become a critical part of our administrative infrastructure, so it would be important to know whether we can improve it, fix issues etc. as a communal effort …or will be essentially paying for a service.

A general comment regarding business models: Since there seem to be a few non-profit organisations here using and contributing to nocodb, we can also talk about public funding, financially supporting the development efforts (as a project hosted by these non-profits). This wouldn't be possible (or at least far more difficult) for proprietary technologies – especially when you'd want funding from a country you're not necessarily located in.

Hope that helps :)

2022-12-12 21:19 UTC, anselmoshim commented
Is there a way I can disable the NocoDB login page entirely so I can just set up my own login page with whichever SSO/SAML provider I want?

2022-12-15 23:13 UTC, flaktrooper commented
I have to admit it is a little concerning to see this being considered as "value add".
SSO is first and foremost a security feature, and I would argue a core one at that. 

Managing separate accounts and permission levels for dozens of volunteers on every single application we deploy is not feasible, and carries a significantly increased risk of mistakes. Paywalling SSO simply means we will have to use another product entirely, because we are not in a position to pay monthly subscription fees for every application we use. This is a feature that is _required_ by more than just enterprise users - I think @ja0nz has suggested an approach that is much more reasonable.

2022-12-16 10:34 UTC, timmwille commented
> I have to admit it is a little concerning to see this being considered as "value add". SSO is first and foremost a security feature, and I would argue a core one at that.
> 
> Managing separate accounts and permission levels for dozens of volunteers on every single application we deploy is not feasible, and carries a significantly increased risk of mistakes. Paywalling SSO simply means we will have to use another product entirely, because we are not in a position to pay monthly subscription fees for every application we use.
> 
> This is a feature that is _required_ by more than just enterprise users - I think @ja0nz has suggested an approach that is much more reasonable.

yes, in most cases it is "I rather pay for good service, then for lock-in or lock-out" - I consider a separate Patch module to be funded already if this won't move but I also do not want provoke endless policy discussions. So maybe it is time to start looking for alternatives. Live and let live. Hopefully it does not end like this (probably will): https://forgejo.org/faq/

2023-01-10 23:39 UTC, o1lab commented
We have been rearchitecting a large part of our application which was released as [beta](https://github.com/nocodb/nocodb/releases/tag/0.101.0-beta.0). So apologies for late reply & thanks for your patience. 

We did consider this request a **FAIR BIT** however we have clearly stated that SSO will be [part of our enterprise edition](https://docs.nocodb.com/FAQs#do-you-plan-to-have-enterprise-edition-) since [long time ago](https://github.com/nocodb/nocodb/blob/develop/packages/noco-docs/content/en/FAQs.md#do-you-plan-to-have-enterprise-edition-). We have a [public roadmap](https://github.com/orgs/nocodb/projects/13/views/2) available here now which also gives a clear picture on what features are (CE) and what are in enterprise edition (EE). And all PRs submitted to relevant edition will be accepted in that edition (similar to Gitlab).

I can understand it is tempting to request most of the features in CE but please do understand this is a fairly large project which involves lot of effort and it is important for us to keep it sustainable. And please do also note our community edition (CE) is much **MORE GIVING** than anything out there in this space (feature list below). 

More than basic features of all no-code database features.
- Email authentication.
- Google auth. 
- All of the roles (super-admin, creator, editor, viewer, commenter).
- Kanban, Survey view / Wizard view
- Locked views
- Row comments. 
- UI access control.
- CSV/JSON download and upload.
- Audit logs. 
- Support for existing databases.
- Support any underlying SQL database to run on.

If @kobim is in agreement  - happy to accept the PR into EE.

2023-01-11 10:10 UTC, ja0nz commented
@o1lab Thank you for the thorough clarification. Not the answer I was hoping for but I still love NocoDB for what it is🙏

2023-01-11 10:49 UTC, timmwille commented
Thank you for clarifying @o1lab → I guess your legal department will have to do a lot of work if you implement AGPL PR from @kobim but for us this is too much taking from the community but not giving back. At some point in the future this might fall on your feet. I still hope the project will survive. For us it is time to move on and look for alternatives...

2023-01-11 10:51 UTC, timmwille commented
@kobim what about a nice community fork? :robot:

2023-01-12 09:27 UTC, syji35 commented
> Thank you for clarifying @o1lab → I guess your legal department will have to do a lot of work if you implement AGPL PR from @kobim but for us this is too much taking from the community but not giving back. At some point in the future this might fall on your feet. I still hope the project will survive. For us it is time to move on and look for alternatives...

We are migrating to Grist, which offers SAML authentication (works with Keycloak for example)

2023-01-13 20:32 UTC, closed without merging

2023-01-16 09:30 UTC, IcedQuinn commented
It's always sad to see ex-open source software start gatekeeping patches out for corpo editions.

2023-01-31 22:18 UTC, jogueber commented
Well free and open source is a wish that you only get if you have it in a foundation setup I guess. 
In apache projects this is more or less standard so quiet sad to see that even PRs from the community are not accepted. 
Usually how these projects then go is that they go to die. 

Because in the end what you see is: people pay for services and are willing to if they feel like they can also control the product. 
Here that seems to be not really the spirit

2023-02-23 21:11 UTC, samuk commented
That's a shame. What's the best alternative at this point? Is it worth forking NocoDB? Or a people going to https://github.com/gristlabs/grist-core instead?

2023-07-03 11:52 UTC, baltazartroisville commented
@o1lab i wish nocodb would cancel google auth, audit log, support for all databases and instead put oidc in for the community edition. that is no enterprise feature at all, even for my family and friends deployment its useful and makes life a lot easier. you could offer enterprise customers still a lot other features like rbac, saml, ldap, customer support, etc.