Save and restore last opened view
nocodb/nocodb pull request #4182
Opened 2022-10-26 13:02 UTC by ketewan

## Change Summary

When switching between tables, make it so that switching back to a table opens last opened view

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [ ] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

2022-10-26 15:58 UTC, bcakmakoglu approved these changes

2022-10-26 15:59 UTC, bcakmakoglu commented
Tests might fail because of the change in logic of having the last opened view active again.

2022-10-27 09:17 UTC, wingkwong requested changes
Tests are required to be updated.

2022-11-04 11:06 UTC, vijayrathore8492 approved these changes

2022-11-09 16:31 UTC, ketewan commented
@wingkwong are there any other changes required? Can we merge it?

2022-11-10 02:06 UTC, merged