Feat: Grid - Single/Multi select add option directly from cell if missing
nocodb/nocodb pull request #4406
Opened 2022-11-16 09:49 UTC by pranavxc

## Change Summary

Provide summary of changes with issue number if any.

## Change type

- [x] feat: (new feature for the user, not a new feature for build script)
- [ ] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

2022-11-21 11:04 UTC, wingkwong requested changes
**issue 1: Renaming tags created by this approach would be all gone.**

Steps to reproduce:

1. Create a tag `foo` by typing in a cell directly
2. Edit column, change option `foo` to something else, says `foo2`
3. The existing data with `foo` will be gone. 

Expected behaviour: records with `foo` will be updated to `foo2`. This works fine if I create an option from EditOrAdd column instead of inputting in cell directly.

2022-11-21 11:50 UTC, pranavxc commented
> **issue 1: Renaming tags created by this approach would be all gone.**
> 
> Steps to reproduce:
> 
> 1. Create a tag `foo` by typing in a cell directly
> 2. Edit column, change option `foo` to something else, says `foo2`
> 3. The existing data with `foo` will be gone.
> 
> Expected behaviour: records with `foo` will be updated to `foo2`. This works fine if I create an option from EditOrAdd column instead of inputting in cell directly.

Fixed

2022-11-21 13:34 UTC, mertmit approved these changes

2022-11-22 03:30 UTC, wingkwong approved these changes

2022-11-22 07:08 UTC, dstala approved these changes
down-arrow in multi select, after pressing escape key - should move to next cell

2022-11-22 07:09 UTC, merged