Fix - Miscellaneous bugs
nocodb/nocodb pull request #4762
Opened 2023-01-05 12:44 UTC by pranavxc

## Change Summary

Provide summary of changes with issue number if any.

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [x] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

2023-01-06 03:19 UTC, wingkwong approved these changes

2023-01-06 04:35 UTC, dstala commented
- [ ] Single select
- click on cell using mouse. cell goes into edit mode; even on `esc` key press, it remains in edit mode
- ideally, on click - we should just stay in select mode; on `double click` or `click + enter`, we should go to edit mode. and `esc` should always toggle mode from edit to select

- [ ] Currency (& Percentage column)
- create currency column
- add 3 rows, insert values into first & second - keep third empty
- copy value from 3rd cell (empty) to second
- cell enters edit mode; value not stored; on press enter, throws error

2023-01-06 04:35 UTC, dstala requested changes
https://github.com/nocodb/nocodb/pull/4762#issuecomment-1373134690

2023-01-11 09:32 UTC, dstala approved these changes

2023-01-11 15:36 UTC, merged