fix: kanban share view issues
nocodb/nocodb pull request #4848
Opened 2023-01-16 06:32 UTC by wingkwong

## Change Summary

- share view goes blank if grouping field is unselected before passing to share view (#4670)
- unexpected data is added when infinite scrolling 
- cover image column displays in ID instead of column title when it is unselected before passing to share view

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [x] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

2023-01-16 12:17 UTC, pranavxc approved these changes

2023-01-17 11:29 UTC, dstala requested changes
shared kanban access in incognito mode redirects to signin page

2023-01-18 05:24 UTC, dstala requested changes
- [x] Filter and Sort broken in Kanban shared view
- [x] UX minor recommendations for shared view
  - Hovering over logo shows an empty tool tip
  - Kanban green logo is barely visible. Possible to turn it to white?

![Screenshot 2023-01-18 at 10 43 00 AM](https://user-images.githubusercontent.com/86527202/213090038-ef1f352f-2e73-4af6-820b-a3f79670aaeb.png)

 - [ ] after fields menu is open, clicking outside should close fields menu. it didn't when clicked outside in red area shown below; similar observation with other tool bar menu items (sort filter download)
![Screenshot 2023-01-18 at 10 47 18 AM](https://user-images.githubusercontent.com/86527202/213090400-b34262ce-d714-423c-89a6-bbb4abd80f0b.png)

- [x] Hide fields in shared kanban, download XLSX; disabled columns should not be part of downloaded header file
![Screenshot 2023-01-18 at 10 52 52 AM](https://user-images.githubusercontent.com/86527202/213091145-71746708-3ed9-4f76-95f5-a385f004f29d.png)

2023-01-18 10:36 UTC, dstala approved these changes

2023-01-18 10:37 UTC, merged