fix: form view field validation error message, use alias name instead…
nocodb/nocodb pull request #4933
Opened 2023-01-26 10:36 UTC by gitstart

## Change Summary
ref: #4919 

use alias name in error message, not original field name

## Change type

- [x] fix: (bug fix for the user, not a fix to a build script)

## Additional information / screenshots (optional)
<img width="1164" alt="Screenshot 2023-01-26 at 11 36 29" src="https://user-images.githubusercontent.com/1501599/214815355-ff9a9f11-57a3-4996-b7d1-e160410a5ba3.png">

Anything for maintainers to be made aware of

2023-01-26 11:03 UTC, wingkwong reviewed
1. Next time please leave a comment in the issue first to ask for assignment to avoid duplicate work (as it has been assigned to someone already).
2. Your change is only partially correct. If I don't set a label, submitting without data would show `null is required`. 
3. The same change should apply to virtual columns as well. You can test it by creating a LTAR column.

2023-01-27 08:48 UTC, gitstart commented
> 1. Next time please leave a comment in the issue first to ask for assignment to avoid duplicate work (as it has been assigned to someone already).
> 2. Your change is only partially correct. If I don't set a label, submitting without data would show `null is required`.
> 3. The same change should apply to virtual columns as well. You can test it by creating a LTAR column.

This is noted

2023-01-31 07:56 UTC, gitstart commented
Hi @wingkwong, the changes has been updated

2023-01-31 08:02 UTC, wingkwong requested changes

2023-01-31 08:02 UTC, wingkwong commented on packages/nc-gui/components/smartsheet/Form.vue
> +                        message: `${element.label ? element.label : element.title} is required`,
`${element.label || element.title}`

2023-01-31 08:02 UTC, wingkwong commented on packages/nc-gui/components/smartsheet/Form.vue
> +                        message: `${element.label ? element.label : element.title} is required`,
`${element.label || element.title}`

2023-01-31 09:13 UTC, gitstart commented on packages/nc-gui/components/smartsheet/Form.vue
> +                        message: `${element.label ? element.label : element.title} is required`,
it has been updated

2023-01-31 09:13 UTC, gitstart commented on packages/nc-gui/components/smartsheet/Form.vue
> +                        message: `${element.label ? element.label : element.title} is required`,
it has been updated

2023-01-31 09:41 UTC, wingkwong approved these changes

2023-01-31 09:42 UTC, merged