add delete and duplicate row buttons to expanded form and grid view
nocodb/nocodb pull request #5035
Opened 2023-02-04 18:52 UTC by spaudanjo

## Change Summary

Contributes to https://github.com/nocodb/nocodb/issues/2101 and adds also a 'Delete row' and 'Duplicate row' menu to the expanded form view. 

## Change type

- [x] feat: (new feature for the user, not a new feature for build script)
- [ ] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

2023-02-06 08:29 UTC, pranavxc commented on packages/nc-gui/components/smartsheet/expanded-form/index.vue
> +  @apply absolute opacity-70 rounded-full transition-transform transition-background transition-opacity transform bg-white hover: (bg-gray-200) active:(scale-125 opacity-100) text-xl;
`hover: (bg-gray-200)` => `hover:(bg-gray-200)`

2023-02-09 09:14 UTC, pranavxc commented
re #2101

2023-02-09 12:44 UTC, pranavxc approved these changes

2023-02-09 16:22 UTC, dstala requested changes
https://www.loom.com/share/08264aab38bd4bffb65510de7eac9518

in fact, when a row is duplicated - we can disable both `duplicate row` and `delete row` option un less its saved

2023-02-13 08:54 UTC, wingkwong commented on packages/nc-gui/components/smartsheet/Gallery.vue
> +        <!-- v-for="(row, rowIndex) of data -->
can be removed

2023-02-13 08:54 UTC, wingkwong commented on packages/nc-gui/components/smartsheet/Gallery.vue
> +// const { xWhere, isPkAvail, isSqlView, eventBus } = useSmartsheetStoreOrThrow()
can be removed

2023-02-13 08:54 UTC, wingkwong commented on packages/nc-gui/components/smartsheet/expanded-form/index.vue
> +    <SmartsheetExpandedFormHeader :view="props.view" @cancel="onClose" @duplicateRow="onDuplicateRow" />
v-on event `@duplicateRow` must be hyphenated

2023-02-14 03:31 UTC, wingkwong approved these changes

2023-02-15 00:56 UTC, spaudanjo commented
the tests lgtm :)

2023-02-15 01:14 UTC, dstala approved these changes

2023-02-15 03:35 UTC, merged