feat: Option to download barcode
nocodb/nocodb pull request #5051
Opened 2023-02-07 06:49 UTC by gitstart

## Change Summary

ref: #4814
option to download barcode

## Change type

- [x] feat: (new feature for the user, not a new feature for build script)

## Test/ Verification

Provide summary of changes.
 Option to download barcode

## Additional information / screenshots (optional)
https://www.loom.com/share/29e2ba9d7f574320af2d4cb9b44e09b1

2023-02-09 09:17 UTC, wingkwong requested changes
**1. Your changes will break the tests.**
 
Please update `tests/playwright/tests/columnBarcode.spec.ts`

**2. The barcode width looks quite different after the change.**

left: your PR, right: 0.104.3

![image](https://user-images.githubusercontent.com/35857179/217768335-28b834ef-4fbf-48e4-9c77-0e94ec7e113c.png)

![image](https://user-images.githubusercontent.com/35857179/217768154-cbd25a21-60d3-4938-a0c1-653fcbb50829.png)

![image](https://user-images.githubusercontent.com/35857179/217768220-c8297fa8-67fd-4532-9af6-3e992f6d6cce.png)

![image](https://user-images.githubusercontent.com/35857179/217768287-e753c65a-4ead-46c6-af1e-b51ef110a44d.png)

![image](https://user-images.githubusercontent.com/35857179/217768666-8c310006-57a4-4be2-8d60-1793ece10da4.png)

2023-02-09 12:48 UTC, pranavxc commented
> 2. The barcode width looks quite different after the change.

@wingkwong Looks like both images are identical but it's stretched to fit the cell. We have to keep the original image aspect ratio then it will be good.

2023-02-09 12:50 UTC, pranavxc commented on packages/nc-gui/components/virtual-cell/barcode/JsBarcodeWrapper.vue
> +    class="w-full"
The `w-full` is breaking the barcode image aspect ratio.

2023-02-09 12:51 UTC, wingkwong commented
@pranavxc Yes. I'm talking about the width being stretched only. The barcode content itself is same.

2023-02-21 05:55 UTC, frankMagoba commented
> **1. Your changes will break the tests.**
> 
> Please update `tests/playwright/tests/columnBarcode.spec.ts`
> 
> **2. The barcode width looks quite different after the change.**
> 
> left: your PR, right: 0.104.3
> 
> ![image](https://user-images.githubusercontent.com/35857179/217768335-28b834ef-4fbf-48e4-9c77-0e94ec7e113c.png)
> 
> ![image](https://user-images.githubusercontent.com/35857179/217768154-cbd25a21-60d3-4938-a0c1-653fcbb50829.png)
> 
> ![image](https://user-images.githubusercontent.com/35857179/217768220-c8297fa8-67fd-4532-9af6-3e992f6d6cce.png)
> 
> ![image](https://user-images.githubusercontent.com/35857179/217768287-e753c65a-4ead-46c6-af1e-b51ef110a44d.png)
> 
> ![image](https://user-images.githubusercontent.com/35857179/217768666-8c310006-57a4-4be2-8d60-1793ece10da4.png)

Hello @wingkwong , I was considering a way to allow for downloading the barcode svgs in light of the test cases being run against svg fixtures. My idea is to include an action button that triggers a download event. However, implementing this would require a recommendation for the UI design of the button used to download the barcodes.

2023-02-21 12:15 UTC, gitstart commented
> **1. Your changes will break the tests.**
> 
> Please update `tests/playwright/tests/columnBarcode.spec.ts`
> 
> **2. The barcode width looks quite different after the change.**
> 
> left: your PR, right: 0.104.3
> 
> ![image](https://user-images.githubusercontent.com/35857179/217768335-28b834ef-4fbf-48e4-9c77-0e94ec7e113c.png)
> 
> ![image](https://user-images.githubusercontent.com/35857179/217768154-cbd25a21-60d3-4938-a0c1-653fcbb50829.png)
> 
> ![image](https://user-images.githubusercontent.com/35857179/217768220-c8297fa8-67fd-4532-9af6-3e992f6d6cce.png)
> 
> ![image](https://user-images.githubusercontent.com/35857179/217768287-e753c65a-4ead-46c6-af1e-b51ef110a44d.png)
> 
> ![image](https://user-images.githubusercontent.com/35857179/217768666-8c310006-57a4-4be2-8d60-1793ece10da4.png)

Hello @wingkwong , I was considering a way to allow for downloading the barcode svgs in light of the test cases being run against svg fixtures. My idea is to include an action button that triggers a download event. However, implementing this would require a recommendation for the UI design of the button used to download the barcodes.

2023-02-22 03:41 UTC, wingkwong commented
You original change is fine. You just need to handle the CSS style issue.

2023-08-29 16:42 UTC, wingkwong commented
Closing - inactivity.

2023-08-29 16:42 UTC, closed without merging