fix: Attachment lookup column bug
nocodb/nocodb pull request #5063
Opened 2023-02-09 06:13 UTC by pranavxc

## Change Summary

- Render attachment cell properly in the lookup
- Render lookup cells in read-only mode

 re #5052 

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [x] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

2023-02-09 07:15 UTC, dstala requested changes
attachment thumbnail in lookup are displayed in one row; prefer to split it up as in attachment column
  
![Screenshot 2023-02-09 at 12 44 34 PM](https://user-images.githubusercontent.com/86527202/217743457-a549c497-1de9-4fdb-9701-5e3e8e924764.png)

2023-02-09 13:49 UTC, pranavxc commented
> attachment thumbnail in lookup are displayed in one row; prefer to split it up as in attachment column
> 
> ![Screenshot 2023-02-09 at 12 44 34 PM](https://user-images.githubusercontent.com/86527202/217743457-a549c497-1de9-4fdb-9701-5e3e8e924764.png)

Fixed :+1:

2023-02-09 15:41 UTC, dstala approved these changes

2023-02-10 02:50 UTC, wingkwong approved these changes

2023-02-10 02:50 UTC, merged