add feature upload xlsx / json in existing table
nocodb/nocodb pull request #5164
Opened 2023-02-19 18:46 UTC by semmjon

## Change Summary

PR for:
- https://github.com/nocodb/nocodb/issues/5021
- https://github.com/nocodb/nocodb/issues/4271

 I added the feature that enables users to upload Excel file templates and import data into an existing table. I accomplished this by modifying the QuickImport.vue file and adding some code to handle the uploading of the new file types. I also updated the ViewActions.vue file to display the new upload options in the project menu, and created a new QuickImportDialogType to differentiate between CSV, Excel, and JSON import options. Users will now be able to easily import data from Excel and JSON files into an existing table.

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [ ] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

The first file, packages/nc-gui/components/dlg/QuickImport.vue, was changed to add support for uploading XLSX and JSON files into an existing table. Specifically, the following changes were made:

importState was changed from being an object created using reactive to a defaultImportState object. The importState variable is now created by making a reactive copy of defaultImportState. This is a best practice when using the reactive API.
A new defaultImportState object was created that defines default values for the fileList, url, jsonEditor, jsonSchema, delimiter, firstRowAsHeaders, and shouldImportData properties.
The handleImport function was modified to set templateEditorModal to false and to reset the importState to its default values after the import is complete.
The second file, packages/nc-gui/components/smartsheet/toolbar/ViewActions.vue, was modified to add support for uploading XLSX and JSON files. Specifically, the following changes were made:

A new QuickImportDialogType type was defined that specifies the different types of import dialogs that can be displayed.
A new quickImportDialogTypes array was defined that contains the different import dialog types.
A new quickImportDialogs object was defined that maps import dialog types to ref variables that control whether the dialog is displayed or not.
The a-menu-item template was modified to loop over each type of import dialog and display a menu item for each.
A new LazyDlgQuickImport component was added to the file. This component takes a v-model prop that controls whether the component is displayed or not. The component is used to display the import dialog when the corresponding menu item is clicked.

Tested locally in a dev-scenario (npm run dev / run:watch) and in a deployed scenario with a dockerfile / helm-chart.

2023-02-20 04:38 UTC, wingkwong requested changes
Uploading a JSON file (either with correct mapping and incorrect one) would cause forever loading with a successful message while it is failing behind the scene. 

![image](https://user-images.githubusercontent.com/35857179/220008695-25c1ee3d-fbd5-42f9-b5e8-db7ae630fea2.png)

You may try csv or excel to see the expected behaviours if there is no correct mapping, namely

- the destination column is not mapped 
- the source column is not checked

![image](https://user-images.githubusercontent.com/35857179/220009221-7576e0ff-d961-4425-9bf2-53bf6c41be94.png)

Otherwise, it should show the correct mapping. Here's the sample json. 

```json
[
    {
        "country": "Country 1",
        "lang": "Language 1",
        "foo": "Bar"
    },
    {
        "country": "Country 2",
        "lang": "Language 2",
        "foo": "Bar"
    }
]
```

2023-02-20 10:00 UTC, semmjon commented
Sry, i dont testet json before. Maybe we'll remove json from the list for now until I have time to test it?

2023-02-20 10:14 UTC, wingkwong commented
You may remove Json one first as I think it requires some extra implementation.

2023-02-20 11:55 UTC, wingkwong commented
whenever it is ready, please click re-request review button to notify me to have a review again.

2023-02-22 06:27 UTC, wingkwong requested changes

2023-02-22 06:27 UTC, wingkwong commented on packages/nc-gui/components/smartsheet/toolbar/ViewActions.vue
> +      :base-id="bases[0].id"
A project can include different bases. You should pass the one that the opened table belongs to.

2023-02-22 06:27 UTC, wingkwong commented on packages/nc-gui/components/smartsheet/toolbar/ViewActions.vue
> +const quickImportDialogs: Record<typeof quickImportDialogTypes[number], Ref<boolean>> = quickImportDialogTypes.reduce(
add line breaks between them.

2023-02-23 03:29 UTC, wingkwong requested changes
Still not catering https://github.com/nocodb/nocodb/pull/5164#discussion_r1113886062

2023-02-24 04:21 UTC, wingkwong approved these changes

2023-02-24 04:21 UTC, merged