fix: Hide column edit option from shared form
nocodb/nocodb pull request #5206
Opened 2023-02-24 12:49 UTC by pranavxc

## Change Summary

- Hide the column edit option from the shared form
- Add logout API for clearing refresh token from cookie and database to avoid automatic token generation in GUI

re #5205

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [ ] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

2023-02-24 13:53 UTC, dstala requested changes
works- verified for both form view & grid view share. 

minor change required, see if you can accommodate with ease
- on hover over column header, mouse icon changes to `click` icon, giving a false impression that its clickable. avoid changing mouse icon

2023-02-27 04:05 UTC, wingkwong commented on packages/nocodb-sdk/src/lib/Api.ts
> +      }),
name is `signout` but path is `signin`. please double check.

2023-02-27 04:05 UTC, wingkwong commented on packages/nocodb-sdk/src/lib/Api.ts
> + * @request POST:/api/v1/auth/user/signout
name is `signout` but path is `signin`. please double check.

2023-02-27 04:05 UTC, wingkwong commented on packages/nocodb-sdk/src/lib/Api.ts
> +        path: `/api/v1/auth/user/signout`,
name is `signout` but path is `signin`. please double check.

2023-02-27 04:05 UTC, wingkwong commented on packages/nocodb/src/schema/swagger.json
> +    "/api/v1/auth/user/signout": {
name is `signout` but path is `signin`. please double check.

2023-02-27 04:36 UTC, dstala reviewed
shared view edit menu bug is fixed. noticing issues with sign-in procedures.

2023-02-27 07:28 UTC, dstala approved these changes

2023-02-27 07:59 UTC, merged