chore: readme typos
nocodb/nocodb pull request #5294
Opened 2023-03-14 08:25 UTC by dammy001

## Change Summary

Provide summary of changes with issue number if any.

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [ ] fix: (bug fix for the user, not a fix to a build script)
- [x] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

2023-03-14 08:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nocodb/nocodb?pullRequest=5294) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nocodb/nocodb?pullRequest=5294) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nocodb/nocodb?pullRequest=5294) it.</sub>

2023-03-14 08:52 UTC, wingkwong requested changes

2023-03-14 08:52 UTC, wingkwong commented on README.md
> +Please refer to the [Environment](https://docs.nocodb.com/getting-started/environment-variables)[ variables](https://docs.nocodb.com/getting-started/environment-variables)](https://docs.nocodb.com/ge
broken

![image](https://user-images.githubusercontent.com/35857179/224946880-a90f436e-9bf6-446a-8931-ce219edb6959.png)

2023-03-14 10:04 UTC, dammy001 commented
@wingkwong fixed

2023-03-14 10:44 UTC, wingkwong requested changes

2023-03-14 10:44 UTC, wingkwong commented on README.md
> +Access Dashboard using: [http://localhost:8080/dashboard](http://localhost:8080/dashboard)](http://localhost:8080/dashboard)
broken here as well

2023-03-14 12:28 UTC, dammy001 commented on README.md
> +Access Dashboard using: [http://localhost:8080/dashboard](http://localhost:8080/dashboard)](http://localhost:8080/dashboard)
resolved @wingkwong

2023-03-15 04:34 UTC, wingkwong approved these changes

2023-03-15 04:34 UTC, merged