feat(lang): add column local dropdown text
nocodb/nocodb pull request #5663
Opened 2023-05-18 12:34 UTC by amajakai14

## Change Summary

Provide summary of changes with issue number if any.

## Change type

- [x] feat: (new feature for the user, not a new feature for build script)
- [ ] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.
showing select option DataType in Local language instead of default value by default

## Additional information / screenshots (optional)
before. 
<img width="440" alt="before_localize" src="https://github.com/nocodb/nocodb/assets/59330424/bd260799-3eff-49d0-b790-c32df3a4d156">
after. 
<img width="438" alt="after_localize" src="https://github.com/nocodb/nocodb/assets/59330424/4d4c3aec-1b57-4091-83e2-49a6225a8cc6">
  
Anything for maintainers to be made aware of

2023-05-18 12:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nocodb/nocodb?pullRequest=5663) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nocodb/nocodb?pullRequest=5663) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nocodb/nocodb?pullRequest=5663) it.</sub>

2023-05-19 05:44 UTC, wingkwong requested changes
prefer the following way for better readability.

```vue
{{ renderColumnType(opt.name) }}
```

```ts
const renderColumnType = (columnType: string) => {
  // when no translation is found, the value of t(`key`) would be `key`
  if (t(`datatype.${columnType}`) !== `datatype.${columnType}`) {
    // if the target translation is available, then use it
    return t(`datatype.${columnType}`)
  }
  // else we use the default one (i.e. English)
  return columnType
}
```

2023-05-19 21:58 UTC, amajakai14 commented
> prefer the following way for better readability.
> 
> ```
> {{ renderColumnType(opt.name) }}
> ```
> 
> ```ts
> const renderColumnType = (columnType: string) => {
>   // when no translation is found, the value of t(`key`) would be `key`
>   if (t(`datatype.${columnType}`) !== `datatype.${columnType}`) {
>     // if the target translation is available, then use it
>     return t(`datatype.${columnType}`)
>   }
>   // else we use the default one (i.e. English)
>   return columnType
> }
> ```

thanks for suggestion!

2023-05-20 02:53 UTC, wingkwong approved these changes

2023-05-20 12:19 UTC, wingkwong requested changes

2023-05-20 12:19 UTC, wingkwong commented on packages/nc-gui/components/smartsheet/column/EditOrAdd.vue
> +  if (locale.value === 'en') return columnType
please revert this change. no need to add that.

2023-06-26 09:33 UTC, wingkwong requested changes

2023-06-26 09:33 UTC, wingkwong commented on packages/nc-gui/components/smartsheet/column/EditOrAdd.vue
> +  if (locale.value === 'en') return columnType
I think this line is not required. If it doesn't match, it will return english one by default.

2024-07-21 04:42 UTC, closed without merging

2024-07-21 04:42 UTC, dstala commented
@amajakai14 closing this for now as its an year old. Please rebase & create a new PR if issue is still relevant.