fix(nocodb):use is-inside-container to account ffor non-docker container runtime
nocodb/nocodb pull request #5704
Opened 2023-05-22 22:50 UTC by lhr0909

## Change Summary

Provide summary of changes with issue number if any.

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [x] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

2023-05-22 22:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nocodb/nocodb?pullRequest=5704) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nocodb/nocodb?pullRequest=5704) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nocodb/nocodb?pullRequest=5704) it.</sub>

2023-05-22 23:01 UTC, lhr0909 commented
@wingkwong I would like to help test this, so if the timely build is available I can load it up on my FlyIO instance and try it out. Then I will report back the test result so we can ship it. Thanks!

2023-05-23 04:52 UTC, wingkwong requested changes
Thanks. LGTM. Please exclude those changes from `nocodb-legacy`? That's a snapshot for the old backend. It's currently not in use and not supposed to update it.

2023-05-23 05:09 UTC, lhr0909 commented
> Thanks. LGTM. Please exclude those changes from `nocodb-legacy`? That's a snapshot for the old backend. It's currently not in use and not supposed to update it.

@wingkwong OK, will do that.

2023-05-23 05:18 UTC, lhr0909 commented
@wingkwong Just made the update. Please review

2023-05-23 05:29 UTC, wingkwong commented
Will merge to `fix/is-inside-container` first since we can't have timely-build on an external PR.

2023-05-23 05:29 UTC, merged