feat: New table data apis endpoints
nocodb/nocodb pull request #5747
Opened 2023-05-26 18:39 UTC by pranavxc

## Change Summary

Provide summary of changes with issue number if any.

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [ ] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

2023-06-16 10:11 UTC, dstala requested changes
- [ ] Links list currently doesn't work as desired for BT
- [ ] Links list for HM returns an extra field
![Screenshot 2023-06-16 at 11 00 30 AM](https://github.com/nocodb/nocodb/assets/86527202/2d5de96b-4156-4fa4-9901-2e9e3b6db1d5)

2023-06-18 17:20 UTC, wingkwong commented on packages/noco-docs/content/en/developer-resources/rest-apis.md
> +| Data | Delete| dbTableRow | tableRowDelete | /api/v1/tables/{tableId}/rows |
`{rowId}` is missing.

2023-06-18 17:20 UTC, wingkwong commented on packages/noco-docs/content/en/developer-resources/rest-apis.md
> +| Data | Get | dbTableRow | tableRowRead | /api/v1/tables/{tableId}/rows/{rowId} |
not found this API in Api.ts

2023-06-22 09:03 UTC, dstala approved these changes

2023-06-22 10:05 UTC, pranavxc commented on packages/noco-docs/content/en/developer-resources/rest-apis.md
> +| Data | Delete| dbTableRow | tableRowDelete | /api/v1/tables/{tableId}/rows |
`{rowId}` is part of the body

2023-06-22 10:05 UTC, pranavxc commented on packages/noco-docs/content/en/developer-resources/rest-apis.md
> +| Data | Get | dbTableRow | tableRowRead | /api/v1/tables/{tableId}/rows/{rowId} |
We will remove these from docs

2023-08-03 11:15 UTC, merged