feat: Drag n drop LTAR and Lookup creation
nocodb/nocodb pull request #5807
Opened 2023-06-02 16:15 UTC by pranavxc

## Change Summary

Provide summary of changes with issue number if any.

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [ ] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

2023-06-06 09:30 UTC, dstala commented
@pranavxc 
one observation- 
while trying to add LTAR/LookUps via this method, i unintentionally re-ordered table entries in left tree view. 
not a deal breaker, but if we can find a way to handle this UX - it would be great.

2023-06-06 10:31 UTC, pranavxc commented
> > > @pranavxc one observation- while trying to add LTAR/LookUps via this method, i unintentionally re-ordered table entries in left tree view. not a deal breaker, but if we can find a way to handle this UX - it would be great.
> > 
> > 
> > If the user is not dropping the table inside Treeview, we should avoid reordering. This way we can take care of the issue.
> 
> sounds good. we can try.

@dstala Done 


https://github.com/nocodb/nocodb/assets/61551451/237e8322-e020-4881-b8bc-a29aab4924ce

2023-06-07 14:15 UTC, dstala requested changes
- [ ] Disable drag-drop of SQL view on table
![Screenshot 2023-06-07 at 7 41 12 PM](https://github.com/nocodb/nocodb/assets/86527202/edd1355c-7764-43be-bb74-c99f700cc85a)

- [ ]Identify drag-drop across projects & block them appropriately
Currently we see a modal similar to what we saw above in case of SQL view; and subsequently fails with `table does not exist`

2023-06-08 16:21 UTC, mertmit approved these changes

2023-06-08 16:22 UTC, merged