feat: bulk update records using UI
nocodb/nocodb pull request #5928
Opened 2023-06-19 23:08 UTC by mertmit

## Change Summary

Re #5045
- This PR allows bulk update on both selected records or all records in a view.
  - Select records (or all records in case you want to update all in current view) then right click

## Change type

- [x] feat: (new feature for the user, not a new feature for build script)

2023-06-20 03:24 UTC, wingkwong commented on packages/nc-gui/components/dlg/BulkUpdate.vue
> +      -->
if these are not in use, suggest to remove.

2023-06-20 03:24 UTC, wingkwong commented on packages/nc-gui/components/dlg/BulkUpdate.vue
> +          Bulk Update All
i18n or add a TODO tag. apply to other texts.

2023-06-20 05:49 UTC, dstala requested changes
- [x] [**Marked by Naveen as not supported**] Sakila ext DB PG table. Actor table. Select all - bulk update. Unable to `undo`. Where as Undo works for smaller subset of bulk update.
- [ ] Good to show all the columns in bulk update modal? I would prefer to see only visible fields (not hidden). Discuss.
- [x] UI background needs to be sorted out when we have many columns to update in bulk modal
![Screenshot 2023-06-20 at 11 27 40 AM](https://github.com/nocodb/nocodb/assets/86527202/3687677f-3ba9-4135-a279-b3d1f6e99e71)

- [x] Bulk update when a filter is enabled threw error (issue not noticed in secondary view)
![Screenshot 2023-06-20 at 11 29 53 AM](https://github.com/nocodb/nocodb/assets/86527202/a5f4c030-d98b-4fe0-9819-21d1d1daa0ee)

2023-06-21 10:22 UTC, dstala approved these changes

2023-06-23 11:42 UTC, dstala commented
- [ ] Long text : let us display bigger block on loading it into bulk upload form instead of toggling to bigger block (text area) on click. This way- clicking on next fields after updating long text doesn't realign blocks
- [ ] Tab doesn't work when navigating between fields in upload form
- [ ] Checkbox, on first load is not aligned (somehow the square box appears at the bottom of circle). I am using chrome.
  
![Screenshot 2023-06-23 at 5 07 39 PM](https://github.com/nocodb/nocodb/assets/86527202/af8c0040-2971-41e9-9e07-b151aa1000f0)

- [ ] Date picker (or time/year picker) : after opening it - escape key should only close picker. Subsequent escape should close Bulk update modal
- [ ] Let us swap close icon with hide icon (eye) in form columns. Hide icon should appear only on hovering over that particular column; otherwise it remains hidden (as in form view). Currently form view hide icon is tad bigger. You can keep reduce its size a bit.
- [ ] Consider removing border (my opinion- ignore if you do not agree) to make it look similar to expanded form.
![Screenshot 2023-06-23 at 5 11 39 PM](https://github.com/nocodb/nocodb/assets/86527202/6245e22f-05ac-4370-9a08-78476c031ac1)

2023-06-27 06:41 UTC, merged