Fixed bug when trying to open a row with a binary encoded uuid as PK
nocodb/nocodb pull request #6017
Opened 2023-07-06 12:11 UTC by VictorMinemu

## Change Summary

Provide summary of changes with issue number if any.

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [x] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.
Added a check on the WherePK constructor to check if the data type on the db is binary(16) and if the pk is a valid uuid.
If it's a uuid then returns it as a Binary.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

2023-07-06 12:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nocodb/nocodb?pullRequest=6017) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nocodb/nocodb?pullRequest=6017) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nocodb/nocodb?pullRequest=6017) it.</sub>

2023-07-06 17:37 UTC, VictorMinemu commented
Added the fix for the equal date filter with columns of DB type timestamp.

2023-07-10 16:49 UTC, pranavxc approved these changes

2023-07-10 16:52 UTC, pranavxc commented
re #6023

2023-07-11 05:20 UTC, wingkwong requested changes

2023-07-11 05:20 UTC, wingkwong commented on packages/nocodb/src/db/conditionV2.ts
> +              } else if (column.ct == 'timestamp') {
`column.ct === 'timestamp'`

2023-07-11 05:20 UTC, wingkwong commented on packages/nocodb/src/db/BaseModelSqlv2.ts
> +
prefer Pranav's version as the readability is much better.

2023-07-11 09:15 UTC, VictorMinemu commented on packages/nocodb/src/db/BaseModelSqlv2.ts
> +
I agree it's much more readable.
Fixed in the last commit

2023-07-11 10:28 UTC, merged