Fixed: form view do not extent text area
nocodb/nocodb pull request #6091
Opened 2023-07-28 09:18 UTC by PyJim

## Change Summary

An issue in Nocodb was addressed, specifically related to the 'nc-form-after-submit-msg' textarea. Previously, the textarea was not extending correctly, resulting in text overflow. To resolve this problem, we added overflow: auto; and height: auto; properties to the .nc-cell-longtext class. As a result, users can now comfortably enter and view large messages within the textarea. This fix was implemented in response to the reported issue with the number #5765.

## Change type

- [ ] fix: (bug fix for the user, not a fix to a build script)

## Test/ Verification
1. create text field
2. create form view
3. create share link
4. enter long text to the form using shared view

## Additional information / screenshots (optional)
![textareaTEST](https://github.com/nocodb/nocodb/assets/88323900/327cc6b7-e6f2-43eb-83e4-13430fe6c30f)

2023-07-28 09:36 UTC, wingkwong reviewed
The behaviour doesn't match with the normal form. Please double check. Also please use utility classes instead of CSS.

### Case 1: when the field is not focused

**Normal Form**

![image](https://github.com/nocodb/nocodb/assets/35857179/f973d5ca-05ea-4ef0-9fde-d6a1dc09bad0)

**Shared Form**

![image](https://github.com/nocodb/nocodb/assets/35857179/a3daad4e-503b-41d5-95e1-2b86d82354d5)

### Case 2: when the field is focused

**Normal Form**

![image](https://github.com/nocodb/nocodb/assets/35857179/3b3e4cd6-3021-498b-ad6d-bbb4caadf353)

**Shared Form**

![image](https://github.com/nocodb/nocodb/assets/35857179/b3ad476d-925b-454f-b8fb-3fc7eb1d1a26)

2023-07-28 14:59 UTC, PyJim commented
Made a few changes

2023-07-28 15:52 UTC, wingkwong requested changes
Your change breaks the basic form. Please verify both form first.

![image](https://github.com/nocodb/nocodb/assets/35857179/bb09d935-a063-4326-bd92-36333b041e27)

2023-07-28 15:56 UTC, PyJim commented
Alright

2023-07-28 16:02 UTC, PyJim commented
With basic form do you mean the unshared form?

2023-07-28 16:09 UTC, wingkwong commented
@PyJim Yes. Basic Form View. You can type something long and un-focus the field. Then you should see the following

![image](https://github.com/nocodb/nocodb/assets/35857179/1a25a772-c070-43f4-8f94-a9d3a9248fd2)

2023-07-28 16:21 UTC, PyJim commented
Oh yeah I had not considered that. Just worked on that as well

2023-07-28 16:22 UTC, PyJim commented
Oh yeah I had not considered that. Just worked on that as well

2023-07-28 16:53 UTC, wingkwong requested changes
Un-focused input on basic form view not aligned with shared form view - with same content. Please verify all the cases first.

![image](https://github.com/nocodb/nocodb/assets/35857179/64425a96-a995-449a-897f-badf5b6e3350)

2023-07-28 17:03 UTC, PyJim commented
Please can I get the content sample you used so I use that for testing?

2023-07-28 17:06 UTC, PyJim commented
Also, based on the content, which one is preferable?

2023-07-28 17:08 UTC, wingkwong commented
You can just randomly type something with multiple lines.

```
wqewq eq
wqeqwe
qwewqewq eq
wqeqwe
qwewqewq eq
wqeqwe
qwewqewq eq
wqeqwe
qwewqewq eq
wqeqwe
qwewqewq eq
wqeqwe
qwewqewq eq
wqeqwe
qwewqewq eq
wqeqwe
qwe
```

2023-07-28 17:18 UTC, PyJim commented
Should be okay now

2023-07-28 17:33 UTC, wingkwong requested changes
Now they are both aligned. However, the expected behaviour is exactly opposite. 

### Expected behaviour

when the field is focused:
![image](https://github.com/nocodb/nocodb/assets/35857179/51b99f0c-43ef-4485-8087-80b9357460fc)

when the field is not focused:
![image](https://github.com/nocodb/nocodb/assets/35857179/343a3041-190b-4c5e-9bef-8a9dab97cad8)

### Current behaviour in this PR


when the field is focused:
![image](https://github.com/nocodb/nocodb/assets/35857179/343a3041-190b-4c5e-9bef-8a9dab97cad8)

when the field is not focused:
![image](https://github.com/nocodb/nocodb/assets/35857179/51b99f0c-43ef-4485-8087-80b9357460fc)

2023-08-07 09:01 UTC, wingkwong commented
Closing - as it has been fixed in #6121.

2023-08-07 09:01 UTC, closed without merging