fix(nc-gui): search implemented for gallery view
nocodb/nocodb pull request #6254
Opened 2023-08-28 14:04 UTC by reenphygeorge

## Change Summary

Implemented search for gallery view

- [x] feat: (new feature for the user, not a new feature for build script)
- [x] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

2023-08-28 14:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nocodb/nocodb?pullRequest=6254) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nocodb/nocodb?pullRequest=6254) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nocodb/nocodb?pullRequest=6254) it.</sub>

2023-08-28 14:34 UTC, dstala requested changes
- [ ] didn't work for non primary value field
- [ ] didn't work when connected to external db (tried with sakila PG)

2023-08-28 14:56 UTC, wingkwong requested changes
Your solution got a few problems. Suggest you read till the end first.

1. By hardcoding `(Title,like,%${search.value.query}%)`, you only assume the column is `Title`. Columns with other names would fail. Also, you cannot use `like` for bigint type. You may check out `xWhere` logic from either `useKanbanViewStore.ts` / `useSmartsheetStore.ts` for reference.

![image](https://github.com/nocodb/nocodb/assets/35857179/33a6569a-03e0-46b8-8755-2d55572c19f0) 

2. After filtering, when you go to another views and switch back, the data should be filtered. In your case, filter text is here but the data is not filtered. This is because you only take care of `reloadViewDataHook` but not the view switch, i.e. the `loadData()` in `watch()`. 

Therefore, I think you may do the following

- undo everything you made
- retrieve `xWhere` from `useSmartsheetStoreOrThrow` in `Gallery.vue`, then pass `xWhere` to `useViewData` as the third parameter.

2023-08-28 14:56 UTC, wingkwong commented on packages/nc-gui/composables/useViewData.ts
> +    console.log(params)
please remove console log.

2023-08-28 15:01 UTC, wingkwong commented
Moreover, I think the search logic got another problem. @dstala please help confirm. probably we may create a new issue for it.

Assuming there are two columns, `Title1` and `Title2`

- setting search as `Title2=123` in View A, the data is shown as expected.
- switch to View B
- switch back to View A
- search become `Title1=123`, the data is shown unexpectedly.

The expected behaviour should be still showing data with `Title2=123`.

2023-08-29 02:57 UTC, wingkwong requested changes

2023-08-29 02:57 UTC, wingkwong commented on packages/nc-gui/composables/useViewData.ts
> +  xWhere?:  ComputedRef<string | undefined>,
Here `xWhere` is useless. you don't need to modify this file at all. In fact, you are passing `xWhere` in `useViewData(meta, view, xWhere)` as the third parameter, which is `where` here.

2023-08-29 14:37 UTC, dstala approved these changes

2023-08-30 04:14 UTC, wingkwong approved these changes

2023-08-30 05:20 UTC, dstala commented
> Moreover, I think the search logic got another problem. @dstala please help confirm. probably we may create a new issue for it.
> 
> Assuming there are two columns, `Title1` and `Title2`
> 
> * setting search as `Title2=123` in View A, the data is shown as expected.
> * switch to View B
> * switch back to View A
> * search become `Title1=123`, the data is shown unexpectedly.
> 
> The expected behaviour should be still showing data with `Title2=123`.

@wingkwong created issue. Also asked Shreyas to redesign search box to include column name info display

2023-08-30 05:26 UTC, dstala approved these changes

2023-08-30 05:26 UTC, merged