NCDBOSS-68 - 🐛 Bug: Deleting a table/project with attachment columns doesn't delete them on filesystem
nocodb/nocodb pull request #6271
Opened 2023-08-30 10:38 UTC by gitstart

Here is the GitStart Ticket for this pull request: [NCDBOSS-68](https://developers.gitstart.com/client/nocodb-oss/ticket/NCDBOSS-68)

- Please mark your PR as "ready for review" when you have completed all requirements.
- Please ensure that your PR is reviewed by at least 2 people after you have completed it.
- Comments for review or requested changes from the upstream client will be notified to you by email and will also show on the [ticket page](https://developers.gitstart.com/client/nocodb-oss/ticket/NCDBOSS-68).
- After the PR is merged on the upstream, please merge this PR.
- If there exist merge conflicts on your current PR and you have to close the PR instead of merging it, please go to the [ticket page](https://developers.gitstart.com/client/nocodb-oss/ticket/NCDBOSS-68) to manually finish the task that is related to this PR.

## Demo

https://www.loom.com/share/6e6ed36c51c04fb683d6283293262029

Happy hacking! 🎉

---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.

2023-08-30 17:59 UTC, wingkwong requested changes
Ideally we should handle in `attachments.service.ts`. If I've set up a storage, says S3, then your solution won't work. You may check out  `fileDelete()` under `packages/nocodb/src/plugins` and implement them.

2023-08-31 15:54 UTC, gitstart commented
> Ideally we should handle in `attachments.service.ts`. If I've set up a storage, says S3, then your solution won't work. You may check out `fileDelete()` under `packages/nocodb/src/plugins` and implement them.

Absolutely, your input is greatly appreciated. To effectively test the deletion on S3 following the feature implementation, we kindly request the S3 credentials for access or any other way we can test it out. Your recommendation to explore the fileDelete() function within packages/nocodb/src/plugins will be instrumental in our testing process.

2023-09-01 06:26 UTC, gitstart commented
> > Ideally we should handle in `attachments.service.ts`. If I've set up a storage, says S3, then your solution won't work. You may check out `fileDelete()` under `packages/nocodb/src/plugins` and implement them.
> 
> Absolutely, your input is greatly appreciated. To effectively test the deletion on S3 following the feature implementation, we kindly request the S3 credentials for access or any other way we can test it out. Your recommendation to explore the fileDelete() function within packages/nocodb/src/plugins will be instrumental in our testing process.

The main problem was related to deleting files from the filesystem, which is why we didn't focus on S3 deletion.

2023-09-01 07:04 UTC, wingkwong commented
> The main problem was related to deleting files from the filesystem, which is why we didn't focus on S3 deletion.

Yes I understand. What you said is Local storage plugin (which is used by default if you haven't set up others). That's why I said you should move the deletion implementation to `plugins/storage/Local.ts`, so that we could delete the files by using something like `await storageAdapter.fileDelete(...)`. By doing so, we can separate the deletion logic for different storage plugins. You may take a look at `fileCreate` for reference.

For other storage types, just keep it as it is at this moment. 

Also for a complete solution, even thought not mentioned in the issue, I think it should also cater the cases like deleting row including attachments & deleting attachment columns. Please feel free to ping me at Discord for discussion.

2023-09-20 09:25 UTC, mayomi1 commented
> > The main problem was related to deleting files from the filesystem, which is why we didn't focus on S3 deletion.
> 
> Yes I understand. What you said is Local storage plugin (which is used by default if you haven't set up others). That's why I said you should move the deletion implementation to `plugins/storage/Local.ts`, so that we could delete the files by using something like `await storageAdapter.fileDelete(...)`. By doing so, we can separate the deletion logic for different storage plugins. You may take a look at `fileCreate` for reference.
> 
> For other storage types, just keep it as it is at this moment.
> 
> Also for a complete solution, even thought not mentioned in the issue, I think it should also cater the cases like deleting row including attachments & deleting attachment columns. Please feel free to ping me at Discord for discussion.

Hi @wingkwong , 

We have pushed the update.

2023-09-20 09:33 UTC, gitstart commented
> > The main problem was related to deleting files from the filesystem, which is why we didn't focus on S3 deletion.
> 
> Yes I understand. What you said is Local storage plugin (which is used by default if you haven't set up others). That's why I said you should move the deletion implementation to `plugins/storage/Local.ts`, so that we could delete the files by using something like `await storageAdapter.fileDelete(...)`. By doing so, we can separate the deletion logic for different storage plugins. You may take a look at `fileCreate` for reference.
> 
> For other storage types, just keep it as it is at this moment.
> 
> Also for a complete solution, even thought not mentioned in the issue, I think it should also cater the cases like deleting row including attachments & deleting attachment columns. Please feel free to ping me at Discord for discussion.

Hi @wingkwong ,

We have pushed the update.

2023-10-30 09:26 UTC, mertmit commented
Hi I truly appreciate effort you've put into this fix, but there are other aspects which need to be figured out.
We allow copy/paste for cells and duplicating tables/bases which reuses same attachments. So it is not promised that a file stays within uploaded table only.

Recently I've added a feature to make image links temporarily available ([NC_SECURE_ATTACHMENTS](https://docs.nocodb.com/getting-started/self-hosted/environment-variables)). Moving forward we are planning to make this default behavior and in this new approach we moved away from using base/tableid in path bc of that reason.

So I agree there should be a delete mechanism for unused attachments but this will definitely require some extra steps and we need to discuss internally on the approach.

I am sincerely sorry for taking this on hold but I will keep you updated after discussing with the team.

2023-11-23 19:50 UTC, Vyerni commented
Is there at least any function or something that allows the app to scan for attachments in file storage, but are not actually present anywhere in the DB? Considering the storage path and name becomes obfuscated it's not something that can be manually done either

2025-05-20 09:20 UTC, closed without merging