fix: cant duplicate single select
nocodb/nocodb pull request #6282
Opened 2023-08-31 14:30 UTC by sreehari2003

## Change Summary

Provide summary of changes with issue number if any.
- closes #5195 

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [ ] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

2023-09-01 14:42 UTC, dstala requested changes
after duplicate, cell shows 'default option value' on click
![Screenshot 2023-09-01 at 8 10 48 PM](https://github.com/nocodb/nocodb/assets/86527202/c2062e53-8fc1-4e90-ad65-cd7b1cc5401a)

2023-09-05 08:03 UTC, o1lab commented
@mertmit to review.

2023-09-06 16:27 UTC, dstala approved these changes

2023-09-06 19:01 UTC, pranavxc requested changes

2023-09-06 19:01 UTC, pranavxc commented on packages/nocodb/src/services/columns.service.ts
> +                  }
I guess we have to do this before splitting ?

2023-09-06 19:01 UTC, pranavxc commented on packages/nocodb/src/services/columns.service.ts
> +                colBody.cdf = colBody.cdf.replace(/'/g, '');
Check previous comment

2023-09-07 14:02 UTC, DarkPhoenix2704 commented
#6323 Includes some fix for this.

2023-09-13 03:41 UTC, dstala commented
> #6323 Includes some fix for this.

Revisit this PR after #6323 is merged

2023-09-13 13:30 UTC, closed without merging