fix: missing ui features in context menu
nocodb/nocodb pull request #6384
Opened 2023-09-15 10:07 UTC by sreehari2003

## Change Summary

Provide summary of changes with issue number if any.

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [x] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

2023-09-15 15:01 UTC, dstala commented
cell context menu & view context menu needs a fix

![Screenshot 2023-09-15 at 8 28 41 PM](https://github.com/nocodb/nocodb/assets/86527202/7de4fb6f-aaee-41c0-9c4e-8f3fc94f831f)
![Screenshot 2023-09-15 at 8 30 21 PM](https://github.com/nocodb/nocodb/assets/86527202/39ba374d-41ae-4447-8781-465d5fec38aa)

2023-09-16 05:22 UTC, mustafapc19 commented
@sreehari2003 
For context menu, use `NcMenu` and `NcMenuItem` generic components similar to ProjectNode

2023-09-18 13:38 UTC, dstala commented
@sreehari2003 for view context menu, font size is not 0.85rem

2023-09-19 14:12 UTC, dstala requested changes
Use generic component for
- Cell right click modal
- Field context menu
- View context menu

2023-09-19 14:15 UTC, dstala approved these changes

2023-09-19 16:19 UTC, mustafapc19 requested changes

2023-09-19 16:19 UTC, mustafapc19 commented on packages/nc-gui/components/smartsheet/header/Menu.vue
> +  @apply text-dropdown flex items-center px-1 py-2 gap-1;
@sreehari2003 

Remove `text-dropdown` and replace it with `text-sm`

2023-09-19 16:19 UTC, mustafapc19 commented on packages/nc-gui/windi.config.ts
> +      fontSize: {
@sreehari2003 Remove this as this is not standard

2023-09-19 16:19 UTC, mustafapc19 commented on packages/nc-gui/components/smartsheet/grid/Table.vue
> +            <NcDivider class="!m-0" />
Remove the margin override and use `NcMenu` and `NcMenuItem` which will take care of this

2023-09-19 16:19 UTC, mustafapc19 commented on packages/nc-gui/components/smartsheet/grid/Table.vue
> +              <NcDivider class="!m-0" />
Same thing as above

2023-09-25 09:16 UTC, merged