Nc fix/ws navigation
nocodb/nocodb pull request #6431
Opened 2023-09-20 16:02 UTC by reenphygeorge

## Change Summary

* New ui for empty workspace.

## Change type

- [x] feat: (new feature for the user, not a new feature for build script)
- [ ] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

2023-09-21 02:27 UTC, dstala requested changes
- [ ] Org level VIEWER (OSS) should not see `Create project` button
![Screenshot 2023-09-21 at 7 55 34 AM](https://github.com/nocodb/nocodb/assets/86527202/42283204-c6fc-46f7-9a27-49d957b5cf75)

2023-10-08 19:02 UTC, reenphygeorge commented
@dstala is there any change needed for this ui ?

2023-10-16 04:29 UTC, wingkwong requested changes
lint as usual

2023-10-16 04:29 UTC, wingkwong commented on packages/nc-gui/components/workspace/EmptyPlaceholder.vue
> +      <div class="flex gap-2 justify mt-1">
if `props.buttons` is removed, then `props` is never used. Hence you can remove it.

2023-10-16 04:29 UTC, wingkwong commented on packages/nc-gui/components/project/EmptyPlaceholder.vue
> +                <div class="label">{{ $t('general.new') }} {{ $t('general.empty') }} {{ $t('objects.project') }}</div>
you can just use `text-base font-medium` since it is one-off. Define in `<style>` when you need it multiple times.

2023-10-16 04:29 UTC, wingkwong commented on packages/nc-gui/components/project/EmptyPlaceholder.vue
> +            Get started by creating a new project ..
apply i18n please

2023-10-16 04:29 UTC, wingkwong commented on packages/nc-gui/components/workspace/EmptyPlaceholder.vue
> +            <div class="mb-[0.5px]">New Project</div>
use `{{ $t('title.newProj') }}` instead.

2023-11-15 03:10 UTC, dstala commented
to be deferred; will be considered once we have mascot ready

2023-11-15 03:10 UTC, closed without merging