fix: expanded form ui
nocodb/nocodb pull request #6521
Opened 2023-09-29 08:12 UTC by sreehari2003

## Change Summary

Provide summary of changes with issue number if any.

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [x] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

2023-09-29 09:58 UTC, sreehari2003 commented
![image](https://github.com/nocodb/nocodb/assets/66205494/9a684b1b-0383-47f4-a8e2-ddca953fda9d)

2023-09-29 12:55 UTC, DarkPhoenix2704 requested changes

2023-09-29 13:44 UTC, DarkPhoenix2704 requested changes

2023-09-29 13:44 UTC, DarkPhoenix2704 commented on packages/nc-gui/components/general/UserIcon.vue
> +    commentOwner?: string
email

2023-09-30 16:49 UTC, sreehari2003 commented
except modal flickering all other are completed

2023-10-02 05:32 UTC, closed without merging