fix: Validate select options before insert
nocodb/nocodb pull request #7070
Opened 2023-11-23 10:57 UTC by pranavxc

## Change Summary

- Re #5492

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [ ] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

2023-11-24 08:47 UTC, dstala requested changes
need fix for v2

2023-11-24 13:40 UTC, dstala approved these changes

2023-11-24 15:48 UTC, dstala commented
- [ ] rename select using add/edit menu. validation kicks in & triggers a false error

2023-11-25 06:10 UTC, merged

2024-05-15 03:53 UTC, Kiss-World commented
API still can't import content that doesn't exist in a singleselect or multiple selection。This function is required