UI/UX fixes - 2 #7210
nocodb/nocodb pull request #7218
Opened 2023-12-13 05:26 UTC by rameshmane7218

## Change Summary

Provide summary of changes with issue number if any.

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [x ] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

2023-12-19 12:13 UTC, mertmit requested changes
Can you also handle when we click `New record - Form` on grid `Save` is grayed out but I might want to save with initial state (with default values only)

2023-12-19 12:15 UTC, rameshmane7218 commented on packages/nc-gui/utils/dataUtils.ts
> +      acc[col.title!] = typeof defalutValue === 'string' ? defalutValue.replace(/^'/, '').replace(/'$/, '') : defalutValue
I will update that

2023-12-19 12:17 UTC, rameshmane7218 commented
> Can you also handle when we click `New record - Form` on grid `Save` is grayed out but I might want to save with initial state (with default values only)

Ya sure, I will enable save button

2023-12-20 15:14 UTC, dstala approved these changes

2023-12-20 15:53 UTC, merged