fix: expanded view not working on shared view and shared bases
nocodb/nocodb pull request #8596
Opened 2024-05-28 09:07 UTC by DarkPhoenix2704

## Change Summary

Provide summary of changes with issue number if any.

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [x] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

2024-05-28 13:36 UTC, dstala commented
@DarkPhoenix2704 please check coderabbit review comments

2024-05-28 13:42 UTC, dstala requested changes
- [ ] expanded record for Kanban, Save record button is enabled even when we have not made changes. needs a fix.
- [x] calendar - wasn't able to expand record from shared view
- [x] code rabbit review comments
- [x] calendar shared base issue after expanding record
https://github.com/nocodb/nocodb/assets/86527202/5e7bee27-fc06-4273-86f8-bdfcab05b058

2024-05-29 04:38 UTC, DarkPhoenix2704 commented on packages/nc-gui/composables/useExpandedFormStore.ts
> +      }
They are dependent, hence required to be in a single try catch

2024-05-29 04:39 UTC, DarkPhoenix2704 commented on packages/nc-gui/components/smartsheet/calendar/MonthView.vue
> +    if (!isUIAllowed('dataEdit')) return
The dragStart is triggered from a HTML Element. Hence no need to null check

2024-05-29 04:40 UTC, DarkPhoenix2704 commented on packages/nc-gui/components/smartsheet/calendar/DayView/DateTimeField.vue
> +    if (!isUIAllowed('dataEdit')) return
The eventListeneers are remove on setTimeout.

2024-05-30 06:12 UTC, dstala approved these changes

2024-05-30 06:12 UTC, merged