feat: add S3 endpoint input
nocodb/nocodb pull request #8886
Opened 2024-06-27 16:39 UTC by jgillich

## Change Summary

This change adds a **S3 endpoint** input value and environment variable for the S3 plugin.

Why? Endpoint can be set on the Minio plugin already, however that one does not support environment variables. Since the S3 protocol is supported by many providers, many of them not using Minio, it makes sense to have this option on the S3 plugin as well.

This change is backwards-compatible, the default endpoint is AWS.

## Change type

- [X] feat: (new feature for the user, not a new feature for build script)
- [ ] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Tested and working with Scaleway object storage

## Additional information / screenshots (optional)

Relevant issues: #4993, #7903

2024-06-27 21:15 UTC, jgillich commented
I noticed the field is not being shown when upgrading from an older version, is something else needed to make that happen?

2024-06-28 20:24 UTC, salim-b commented
The newly introduced `NC_S3_ENDPOINT` env var should be [documented](https://docs.nocodb.com/getting-started/self-hosted/environment-variables/) (in [`packages/noco-docs/docs/020.getting-started/050.self-hosted/020.environment-variables.md`](https://github.com/nocodb/nocodb/blob/develop/packages/noco-docs/docs/020.getting-started/050.self-hosted/020.environment-variables.md)).

2024-06-29 11:29 UTC, jgillich commented
@salim-b Thanks, done

Also fixed merge conflicts. Sorry for ignoring Code Rabbit but all of its suggestions range from pointless to potentially dangerous. A stanard linter would do a much better job tbh

2024-07-17 00:57 UTC, vjm commented
i would love to see this merged in order to use minio -- is there a path to get this merged?

2024-07-20 12:25 UTC, mertmit requested changes
Hi @jgillich thank you for your contribution, I've just rebased your code to latest develop and asked some quick changes. Please see those when possible so we can continue with the merge process.

2024-07-20 12:25 UTC, mertmit commented on packages/nocodb/src/plugins/s3/S3.ts
> +      endpoint: this.input.endpoint,
```suggestion
```

Please remove this line as you are checking & appending it on next block

2024-07-20 12:25 UTC, mertmit commented on packages/nocodb/src/plugins/s3/S3.ts
> +        let endpoint = this.input.endpoint
```suggestion
        const endpoint = this.input.endpoint
```
Please use const here instead of let

2024-07-20 18:21 UTC, jgillich commented
@mertmit Thank you, I implemented your suggestions

2024-07-20 19:31 UTC, mertmit approved these changes

2024-07-20 20:22 UTC, pranavxc approved these changes

2024-07-22 07:20 UTC, merged