🖱 Add `title` attribute to `AdvancedOptions.vue` on mouse hover
nocodb/nocodb pull request #9132
Opened 2024-08-01 09:05 UTC by bdsoha

## Change Summary

Add `title` attribute to `AdvancedOptions.vue` to display the full name of the helper columns on mouse hover.

## Change type

- [x] feat: (new feature for the user, not a new feature for build script)

2024-08-01 09:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nocodb/nocodb?pullRequest=9132) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nocodb/nocodb?pullRequest=9132) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nocodb/nocodb?pullRequest=9132) it.</sub>

2024-08-01 09:09 UTC, o1lab commented
@bdsoha : thanks for the contribution. Please the sign the CLA

2024-08-01 09:11 UTC, bdsoha commented
@o1lab Signed!

2024-08-07 14:42 UTC, rameshmane7218 requested changes

2024-08-07 14:42 UTC, rameshmane7218 commented on packages/nc-gui/components/smartsheet/column/AdvancedOptions.vue
Instead of adding title attribute on input/checkbox add it on `a-form-item` so that if user hover on label it will show.

**Note:**
- If we added `label` attribute on `a-form-item` internally it will add title attribute to label which is same as `label` attribute value.
- To update this you have to use slot to render label as shown in below code

```ts
 <a-form-item>
    <template #label>
      <span title="Auto Increment">AI</span>
    </template>
    <a-checkbox
      v-model:checked="vModel.ai"
      :disabled="sqlUi.colPropUNDisabled(vModel) || !sqlUi.columnEditable(vModel)"
      class="nc-column-checkbox-AI"
     
      @change="onAlter"
    />
</a-form-item>
```

2024-08-08 05:40 UTC, rameshmane7218 approved these changes

2024-08-08 05:57 UTC, merged