feat: Implement scanFiles for gcs and Minio
nocodb/nocodb pull request #9463
Opened 2024-09-10 18:02 UTC by DarkPhoenix2704

## Change Summary

Implement scanFiles for gcs and Minio

Closes https://github.com/nocodb/nocodb/issues/9450

## Change type

- [x] feat: (new feature for the user, not a new feature for build script)

2024-09-11 20:20 UTC, mertmit requested changes

2024-09-11 20:20 UTC, mertmit commented on packages/nocodb/src/plugins/gcs/Gcs.ts
> +    });
Would this work for huge number of files? Even so it is not a good idea to load all into memory at once.
Can we use getFilesStream instead?

2024-09-11 22:45 UTC, dolsem commented on packages/nocodb/src/plugins/gcs/Gcs.ts
> +    stream.push(null);
To address @mertmit's comment:
```suggestion
    this.storageClient.bucket(this.bucketName).getFilesStream({
      prefix: globPattern.replace(/^\*/, ''),
      autoPaginate: true,
    })
      .on('error', (err) => {
        stream.destroy(err);
      })
      .on('data', (file) => {
        stream.push(file.name);
      })
      .on('end', () => {
        stream.push(null);
      });
```

2024-09-15 10:29 UTC, mertmit approved these changes

2024-09-15 14:45 UTC, merged