AWS IAM Role support
nocodb/nocodb pull request #9642
Opened 2024-10-11 15:28 UTC by Upgreydd

## Change Summary

Correct AWS IAM role handling

## Change type

- [X] feat: (new feature for the user, not a new feature for build script)
- [X] fix: (bug fix for the user, not a fix to a build script)
- [X] docs: (changes to the documentation)
- [X] style: (formatting, missing semi colons, etc; no production code change)
- [X] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

2024-10-12 06:09 UTC, sinanmohd requested changes

2024-10-12 06:09 UTC, sinanmohd commented on packages/nocodb/src/plugins/GenericS3/GenericS3.ts
> +    this.input = input as GenericObjectStorageInput;
it would be nice if you could use `constructor(protected input: GenericObjectStorageInput) {}`

2024-10-12 06:09 UTC, sinanmohd commented on packages/noco-docs/docs/020.getting-started/050.self-hosted/020.environment-variables.md
> +| `NC_ATTACHMENT_EXPIRE_SECONDS` | No        | Time in seconds after which pre-signed URLs for attachments start to expire. The actual expiration will occur after this time plus an additional 10 minu
Please split up your changes into two commits that follow the commit message convention
something along the lines of
- style: ***
- feat: ***

2024-10-12 06:37 UTC, Upgreydd commented
@coderabbitai full review

2024-10-12 06:56 UTC, Upgreydd commented
@sinanmohd please re-review.

2024-10-12 08:12 UTC, sinanmohd approved these changes

2024-10-14 07:27 UTC, o1lab approved these changes

2024-10-14 09:11 UTC, merged